namespace Bubble.Core.Datacenter.Datacenter.Effects;

public enum ActionId 
{
    InvalidAction = -1,
    CharacterChangeMap = 2,
    CharacterChangeRespawnMap,
    CharacterTeleportOnSameMap,
    CharacterPush,
    CharacterPull,
    CharacterDivorceWifeOrHusband,
    CharacterExchangePlaces,
    CharacterDodgeHit,
    CharacterLearnEmoticon,
    CharacterCreateGuild = 12,
    QuestObjectiveValidate = 30,
    QuestStepValidate,
    QuestQuestValidate,
    QuestStart = 34,
    QuestReset = 36,
    QuestForceStart,
    BreachCreate = 46,
    BreachEnter,
    BreachNextFightRoom,
    BreachNextSafeRoom,
    CarryCharacter,
    ThrowCarriedCharacter,
    BreachPreviousRoom,
    BreachJumpToSafeRoom,
    BreachKickOut,
    BreachModifyMap,
    BreachDisplayRoomsRewards,
    BreachGainBonus,
    BreachModifyRoom,
    BreachModifyFightModifier = 60,
    BreachModifyBoss,
    BreachAddBoss,
    AnomalyExit,
    CharacterMovementPointsSteal = 77,
    CharacterMovementPointsWin,
    CharacterMultiplyReceivedDamageOrGiveLifeWithRatio,
    CharacterLifePointsLostFromPush,
    CharacterLifePointsWinWithoutElement,
    CharacterLifePointsStealWithoutBoost,
    CharacterActionPointsSteal = 84,
    CharacterLifePointsLostBasedOnCasterLifeFromWater,
    CharacterLifePointsLostBasedOnCasterLifeFromEarth,
    CharacterLifePointsLostBasedOnCasterLifeFromAir,
    CharacterLifePointsLostBasedOnCasterLifeFromFire,
    CharacterLifePointsLostBasedOnCasterLife,
    CharacterDispatchLifePointsPercent,
    CharacterLifePointsStealFromWater,
    CharacterLifePointsStealFromEarth,
    CharacterLifePointsStealFromAir,
    CharacterLifePointsStealFromFire,
    CharacterLifePointsSteal,
    CharacterLifePointsLostFromWater,
    CharacterLifePointsLostFromEarth,
    CharacterLifePointsLostFromAir,
    CharacterLifePointsLostFromFire,
    CharacterLifePointsLost,
    CharacterActionPointsLost,
    CharacterLifeLostModerator = 105,
    CharacterSpellReflector,
    CharacterLifeLostReflector,
    CharacterLifePointsWinFromFire,
    CharacterLifePointsLostCaster,
    CharacterBoostLifePoints,
    CharacterBoostActionPoints,
    CharacterBoostDamages,
    CharacterBoostCriticalHit = 115,
    CharacterDeboostRange,
    CharacterBoostRange,
    CharacterBoostStrength,
    CharacterBoostAgility,
    CharacterActionPointsWin,
    CharacterBoostDamagesForAllGame,
    CharacterBoostCriticalMiss,
    CharacterBoostChance,
    CharacterBoostWisdom,
    CharacterBoostVitality,
    CharacterBoostIntelligence,
    CharacterMovementPointsLost,
    CharacterBoostMovementPoints,
    CharacterStealGold = 130,
    CharacterRemoveAllEffects = 132,
    CharacterActionPointsLostCaster,
    CharacterMovementPointsLostCaster,
    CharacterBoostRangeCaster = 136,
    CharacterBoostDamagesCaster,
    CharacterBoostDamagesPercent,
    CharacterEnergyPointsWin,
    CharacterPassNextTurn,
    CharacterKill,
    CharacterBoostPhysicalDamages,
    CharacterLifePointsWinWithoutBoost,
    CharacterLifePointsLostNoBoost,
    CharacterDeboostDamages,
    CharacterCurse,
    CharacterResurectAllyInFight,
    CharacterAddFollowingCharacter,
    CharacterChangeLook,
    CharacterMakeInvisible,
    CharacterDeboostChance = 152,
    CharacterDeboostVitality,
    CharacterDeboostAgility,
    CharacterDeboostIntelligence,
    CharacterDeboostWisdom,
    CharacterDeboostStrength,
    CharacterBoostMaximumWeight,
    CharacterDeboostMaximumWeight,
    CharacterBoostActionPointsLostDodge,
    CharacterBoostMovementPointsLostDodge,
    CharacterDeboostActionPointsLostDodge,
    CharacterDeboostMovementPointsLostDodge,
    CharacterBoostOneWeaponDamagePercent = 165,
    CharacterDeboostActionPoints = 168,
    CharacterDeboostMovementPoints,
    CharacterDeboostCriticalHit = 171,
    CharacterDeboostMagicalReduction,
    CharacterDeboostPhysicalReduction,
    CharacterBoostInitiative,
    CharacterDeboostInitiative,
    CharacterBoostMagicFind,
    CharacterDeboostMagicFind,
    CharacterBoostHealBonus,
    CharacterDeboostHealBonus,
    CharacterAddDoubleUseSummonSlot,
    SummonCreature,
    CharacterBoostMaximumSummonedCreatures,
    CharacterBoostMagicalReduction,
    CharacterBoostPhysicalReduction,
    CharacterDeboostDamagesPercent = 186,
    CharacterAlignmentSideSet = 188,
    CharacterInventoryRemoveItem = 192,
    CharacterInventoryAddItemCheck,
    CharacterInventoryGainKamas,
    CharacterTransform = 197,
    DecorsRevealUnvisible = 202,
    CharacterResurrection = 206,
    CharacterBoostEarthElementPercent = 210,
    CharacterBoostWaterElementPercent,
    CharacterBoostAirElementPercent,
    CharacterBoostFireElementPercent,
    CharacterBoostNeutralElementPercent,
    CharacterDeboostEarthElementPercent,
    CharacterDeboostWaterElementPercent,
    CharacterDeboostAirElementPercent,
    CharacterDeboostFireElementPercent,
    CharacterDeboostNeutralElementPercent,
    CharacterReflectorUnboosted,
    CharacterInventoryAddItemRandomNocheck,
    CharacterInventoryAddItemFromRandomDrop,
    CharacterBoostTrap = 225,
    CharacterBoostTrapPercent,
    CharacterGainRide = 229,
    CharacterEnergyLossBoost,
    DecorsPlayAnimationD2 = 237,
    PlayCinematic = 239,
    CharacterBoostEarthElementResist,
    CharacterBoostWaterElementResist,
    CharacterBoostAirElementResist,
    CharacterBoostFireElementResist,
    CharacterBoostNeutralElementResist,
    CharacterDeboostEarthElementResist,
    CharacterDeboostWaterElementResist,
    CharacterDeboostAirElementResist,
    CharacterDeboostFireElementResist,
    CharacterDeboostNeutralElementResist,
    CharacterLifeLostCasterModerator = 265,
    CharacterStealChance,
    CharacterStealVitality,
    CharacterStealAgility,
    CharacterStealIntelligence,
    CharacterStealWisdom,
    CharacterStealStrength,
    CharacterLifePointsLostBasedOnCasterLifeMissingFromWater = 275,
    CharacterLifePointsLostBasedOnCasterLifeMissingFromEarth,
    CharacterLifePointsLostBasedOnCasterLifeMissingFromAir,
    CharacterLifePointsLostBasedOnCasterLifeMissingFromFire,
    CharacterLifePointsLostBasedOnCasterLifeMissing,
    BoostSpellRangeMin,
    BoostSpellRangeMax,
    BoostSpellRangeable,
    BoostSpellDmg,
    BoostSpellHeal,
    BoostSpellApCost,
    BoostSpellCastIntvl,
    BoostSpellCc,
    BoostSpellCastoutline,
    BoostSpellNolineofsight,
    BoostSpellMaxperturn,
    BoostSpellMaxpertarget,
    BoostSpellCastIntvlSet,
    BoostSpellBaseDmg,
    DeboostSpellRangeMax,
    DeboostSpellRangeMin,
    DeboostSpellApCost,
    DeboostOccupiedCell,
    DeboostFreeCell,
    BoostFreeCell,
    FightDispellTemporaryObject = 310,
    BoostOccupiedCell = 314,
    CharacterStealRange = 320,
    CharacterChangeColor = 333,
    CharacterAddAppearance = 335,
    RefreshMapNpcOnlyForMeInRoleplay = 350,
    RefreshMapNpcForEveryoneInRoleplay,
    FightAddTrapCastingSpell = 400,
    FightAddGlyphCastingSpell,
    FightAddGlyphCastingSpellEndturn,
    FightKillAndSummon = 405,
    CharacterDispellSpell,
    CharacterLifePointsWinNoBoost,
    CharacterBoostApAttack = 410,
    CharacterDeboostApAttack,
    CharacterBoostMpAttack,
    CharacterDeboostMpAttack,
    CharacterBoostPushDamage,
    CharacterDeboostPushDamage,
    CharacterBoostPushDamageReduction,
    CharacterDeboostPushDamageReduction,
    CharacterBoostCriticalDamagesBonus,
    CharacterDeboostCriticalDamagesBonus,
    CharacterBoostCriticalDamagesReduction,
    CharacterDeboostCriticalDamagesReduction,
    CharacterBoostEarthDamages,
    CharacterDeboostEarthDamages,
    CharacterBoostFireDamages,
    CharacterDeboostFireDamages,
    CharacterBoostWaterDamages,
    CharacterDeboostWaterDamages,
    CharacterBoostAirDamages,
    CharacterDeboostAirDamages,
    CharacterBoostNeutralDamages,
    CharacterDeboostNeutralDamages,
    CharacterActionPointsStealNoEvade = 440,
    CharacterMovementPointsStealNoEvade,
    ChangeCompassByCoord = 509,
    AddPrism = 513,
    ShowTaxCollectorList = 516,
    ExchangeDecraftOpen,
    GotoWaypoint = 600,
    CharacterLearnSpellLevel = 604,
    CharacterGainXp,
    CharacterGainWisdom,
    CharacterGainStrength,
    CharacterGainChance,
    CharacterGainAgility,
    CharacterGainVitality,
    CharacterGainIntelligence,
    CharacterGainStatsPoints,
    CharacterGainJobXp = 614,
    CharacterReadBook = 620,
    CharacterSummonMonster,
    GotoHouse,
    CharacterSummonMonsterGroup,
    CharacterResetCharacs = 626,
    CharacterSummonMonsterGroupDynamic = 628,
    CharacterLearnSpell,
    CharacterSendInformationText,
    CharacterSendErrorText = 632,
    CharacterGainHonour = 640,
    CharacterLooseHonour = 642,
    MapResurectionAllies = 645,
    MapHealAllies,
    MapForceEnnemiesGhost,
    ForceEnnemyGhost,
    FakeAlignment,
    SetStatedElementState = 652,
    InstanciedmapLeave = 654,
    Noop = 666,
    KillFight,
    Incarnation = 669,
    CharacterLifePointsLostBasedOnCasterLifeReducedByCaster,
    CharacterLifePointsLostBasedOnCasterLifeNotReduced,
    CharacterLifePointsLostBasedOnCasterLifeMidlife,
    ItemChangeEffect = 700,
    ItemAddEffect,
    CaptureSoul = 705,
    CaptureRide,
    ItemEquipPreset,
    CharacterAddCostToAction = 710,
    LadderSuperrace = 715,
    LadderRace,
    LadderId,
    PvpLadder = 720,
    CharacterLearnSpellTemporary = 722,
    GainTitle = 724,
    CharacterRenameInvalidGuild,
    GainOrnament,
    TeleportNearestPrism = 730,
    AutoAggressEnemyPlayer,
    ResistAutoAggress,
    BoostSoulCaptureBonus = 750,
    BoostRideXpBonus,
    CharacterBoostTakleEvade,
    CharacterBoostTakleBlock,
    CharacterDeboostTakleEvade,
    CharacterDeboostTakleBlock,
    RemoveOnMove = 760,
    CharacterSacrify = 765,
    ClockwiseConfusionDegree = 770,
    ClockwiseConfusionPi2,
    ClockwiseConfusionPi4,
    CounterClockwiseConfusionDegree,
    CounterClockwiseConfusionPi2,
    CounterClockwiseConfusionPi4,
    CharacterBoostPermanentDamagePercent,
    CharacterDeboostPermanentDamagePercent,
    CharacterChangeRespawnMapByRef,
    CharacterTeleportOnPreviousMap,
    CharacterSummonDeadAllyInFight,
    CharacterUnlucky,
    CharacterMaximizeRoll,
    CharacterPushUpTo,
    CharacterTeleportToFightStartPos,
    CharacterHealAttackers = 786,
    CharacterPunishment = 788,
    CharacterLooseAllItemsFromCategory,
    TargetExecuteSpell = 792,
    TargetExecuteSpellWithAnimation,
    HuntTool = 795,
    CharacterRestoreRespawnMap,
    BoostVisibleTargetOnCellOn = 798,
    BoostVisibleTargetOnCellOff,
    ItemChangeDuration = 805,
    ItemPetsShape,
    ItemPetsEat,
    PetsLastMeal,
    Size = 810,
    ItemBuffChangeDuration,
    ItemChangeDurability,
    ItemUpdateDate,
    ItemDungeonKeyDate,
    ItemFmLostPower,
    ItemResetDate,
    ItemBuffChangeDurationWin,
    ItemBuffChangeDurationLose,
    ItemTeleportForce = 825,
    ItemTeleportMapReference,
    FightChallengeAgainstMonster = 905,
    FightChallengeMixedVersusMonster = 911,
    CharacterSendNotificationText = 916,
    CharacterSendNotificationAlertText,
    PetSetPowerBoost = 939,
    PetPowerBoost,
    FarmTempWithdrawItem = 946,
    FarmWithdrawItem,
    FarmPlaceItem,
    MountRide,
    FightSetState,
    FightUnsetState,
    FightDisableState,
    CreatedSince = 963,
    ShowPlayername,
    ItemLivingId = 970,
    ItemLivingMood,
    ItemLivingSkin,
    ItemLivingCategory,
    ItemLivingLevel,
    MarkNeverTradableStrong = 981,
    MarkNeverTradable,
    MarkNotTradable,
    MarkLegitOwner,
    SetCraftermage,
    MarkTarget,
    SetOwner,
    SetCrafter,
    SeekTarget,
    ShowText,
    RideInvalid = 994,
    RideDetails,
    ItemTeleport = 999,
    FarmObjetEfficacity = 1007,
    SummonBomb,
    CharacterActivateBomb,
    SummonSlave = 1011,
    CharacterLifePointsLostBasedOnMovementPoints,
    CharacterLifePointsLostBasedOnMovementPointsFromAir,
    CharacterLifePointsLostBasedOnMovementPointsFromWater,
    CharacterLifePointsLostBasedOnMovementPointsFromFire,
    CharacterLifePointsLostBasedOnMovementPointsFromEarth,
    TargetExecuteSpellOnSource,
    SourceExecuteSpellOnTarget,
    SourceExecuteSpellOnSource,
    CharacterBoostShieldBasedOnCasterLevel,
    CharacterPushForce,
    CharacterPullForce,
    CharacterExchangePlacesForce,
    CharacterAddIllusionRandom,
    ForceTrapTrigger,
    ForceGlyphTrigger,
    BombComboBonus,
    BombTriggerPowder,
    CharacterVanish,
    FightAddPowderCastingSpell,
    CharacterPassCurrentTurn,
    MarkLegitOwnerTimestamp,
    CharacterDeboostVitalityPercentStatic,
    CharacterSummonDeadAllyAsSummonInFight,
    CharacterAddSpellCooldown,
    CharacterRemoveSpellCooldown,
    CharacterLifePointsWinZobal,
    CharacterAura,
    CharacterBoostShieldBasedOnCasterLife,
    CharacterBoostShield,
    CharacterGetPushed,
    CharacterGetPulled,
    CharacterPullUpTo,
    CharacterProtectionFromSpell,
    CharacterSetSpellCooldown,
    CharacterLifePointsMalus = 1047,
    CharacterLifePointsMalusPercent,
    CharacterGainLevel,
    CharacterResumeDungeon = 1052,
    CharacterBoostDamagesPercentSpells = 1054,
    CharacterClearDungeonSave,
    StaticValueModify = 1057,
    StaticValueSet,
    CharacterAddScaleFlat = 1060,
    CharacterShareDamages,
    CharacterLifePointsLostNoBoostFromEarth = 1063,
    CharacterLifePointsLostNoBoostFromAir,
    CharacterLifePointsLostNoBoostFromWater,
    CharacterLifePointsLostNoBoostFromFire,
    CharacterLifePointsLostBasedOnTargetLifeFromAir,
    CharacterLifePointsLostBasedOnTargetLifeFromWater,
    CharacterLifePointsLostBasedOnTargetLifeFromFire,
    CharacterLifePointsLostBasedOnTargetLifeFromEarth,
    CharacterLifePointsLostBasedOnTargetLife,
    CharacterTaunt,
    ItemChangeEffectSafe,
    MeetingPoint,
    CharacterShortenActiveEffectsDuration,
    CharacterBoostResistPercent,
    CharacterDeboostResistPercent,
    CharacterBoostVitalityPercentStatic,
    CharacterDeboostActionPointsDodgeable,
    CharacterDeboostMovementPointsDodgeable,
    ItemExtraPods,
    ItemGiftOpen,
    ItemGiftPacking,
    ItemGiftContent,
    ItemGiftQuantity,
    ItemGiftTarget,
    ItemGiftChooseTarget,
    FightAddGlyphAura = 1091,
    CharacterLifePointsLostBasedOnTargetMissingMaxLife,
    CharacterLifePointsLostBasedOnTargetMissingMaxLifeAir,
    CharacterLifePointsLostBasedOnTargetMissingMaxLifeFire,
    CharacterLifePointsLostBasedOnTargetMissingMaxLifeWater,
    CharacterLifePointsLostBasedOnTargetMissingMaxLifeEarth,
    CharacterAddIllusionMirror,
    ItemCurseUsedItem,
    FightRollbackTurnBeginPosition,
    FightRollbackPreviousPosition,
    FightTeleswap,
    SpeakingItem,
    FightPushNoDamage,
    FightTeleswapMirror,
    FightTeleswapMirrorCaster,
    FightTeleswapMirrorImpactPoint,
    ItemGuildRename,
    ItemGuildEmblemChange,
    FightLifePointsWinPercent,
    ItemSummonMonsterRewardRate,
    ItemSummonMonsterGroupMaxLootShares,
    CharacterLifePointsLostBasedOnCasterMissingMaxLife = 1118,
    CharacterLifePointsLostBasedOnCasterMissingMaxLifeAir,
    CharacterLifePointsLostBasedOnCasterMissingMaxLifeFire,
    CharacterLifePointsLostBasedOnCasterMissingMaxLifeWater,
    CharacterLifePointsLostBasedOnCasterMissingMaxLifeEarth,
    FightSplashRawTakenDamage,
    FightSplashRawTakenDamageNeutral,
    FightSplashRawTakenDamageAir,
    FightSplashRawTakenDamageFire,
    FightSplashRawTakenDamageWater,
    FightSplashRawTakenDamageEarth,
    CharacterManaUseKillLifeAir = 1131,
    CharacterManaUseKillLifeWater,
    CharacterManaUseKillLifeFire,
    CharacterManaUseKillLifeNeutral,
    CharacterManaUseKillLifeEarth,
    CharacterMovementUseKillLifeAir,
    CharacterMovementUseKillLifeWater,
    CharacterMovementUseKillLifeFire,
    CharacterMovementUseKillLifeNeutral,
    CharacterMovementUseKillLifeEarth,
    AchievementObjectiveValidate = 1142,
    FightBoostWeaponDamagePower = 1144,
    ItemAllianceEmblemChange,
    ItemAllianceRename,
    CharacterGainXpWithLevel = 1149,
    RefreshElement,
    ItemMimicryObjGid,
    MarkNotTradableBackup,
    AddTaxCollector,
    AddPrismModule,
    ItemTeleportMapReferenceForce,
    CharacterMultiplyReceivedHeal = 1159,
    CasterExecuteSpell,
    SetCompanion,
    ChangeCompassByRef,
    CharacterMultiplyReceivedDamage,
    CharacterGiveLifeWithRatio,
    FightAddGlyphCastingSpellImmediate,
    FightBoostGlyphDamagePower,
    FightBoostRuneDamagePower,
    GetPortalQuest,
    UsePortal,
    GetTreasureQuest,
    CharacterBoostDealtDamagePercentMultiplier,
    CharacterDeboostDealtDamagePercentMultiplier,
    GetLegendaryTreasureQuest,
    StopXp,
    CastStartingSpell,
    ItemWrapperLookObjGid,
    ItemTeleportNextMap,
    ItemTeleportPreviousMap,
    ItemWrapperCompatibleObjType,
    FightAddPortal = 1181,
    FightUsePortal,
    FightDisablePortal,
    CharacterGainJobLevelFromLevelOne,
    ItemResetEffects,
    RideHarnessGid = 1187,
    RideGainCapacity,
    CharacterAddDoubleNoSummonSlot,
    FightSplashFinalTakenDamage = 1223,
    FightSplashFinalTakenDamageNeutral,
    FightSplashFinalTakenDamageAir,
    FightSplashFinalTakenDamageFire,
    FightSplashFinalTakenDamageWater,
    FightSplashFinalTakenDamageEarth,
    EnableControlEntityByFightOwner = 2010,
    DisableControlEntityByFightOwner,
    TargetExecuteSpellOnSourceGlobalLimitation = 2017,
    DispelGlyphsOfTarget,
    DispelTrapsOfTarget,
    FightSplashHeal,
    NuggetsRepartition,
    FightAddRuneCastingSpell,
    ForceRuneTrigger,
    DispelRunesOfTarget,
    CharacterOpenHavenbagStorage,
    CharacterHavenbagLottery,
    ControlEntity,
    InheriteCharac,
    FinishMove,
    CharacterLearnFinishMove,
    CharacterLearnHavenBagTheme,
    CasterExecuteSpellGlobalLimitation = 2160,
    TargetExecuteSpellGlobalLimitation = 2792,
    TargetExecuteSpellWithAnimationGlobalLimitation,
    TargetExecuteSpellOnCell,
    TargetExecuteSpellOnCellGlobalLimitation,
    FightKillAndSummonSlave,
    CharacterLearnSmileyPack,
    CharacterBoostDealtDamagePercentMultiplierMelee = 2800,
    CharacterDeboostDealtDamagePercentMultiplierMelee,
    CharacterBoostReceivedDamagePercentMultiplierMelee,
    CharacterDeboostReceivedDamagePercentMultiplierMelee,
    CharacterBoostDealtDamagePercentMultiplierDistance,
    CharacterDeboostDealtDamagePercentMultiplierDistance,
    CharacterBoostReceivedDamagePercentMultiplierDistance,
    CharacterDeboostReceivedDamagePercentMultiplierDistance,
    CharacterBoostDealtDamagePercentMultiplierWeapon,
    CharacterDeboostDealtDamagePercentMultiplierWeapon,
    CharacterBoostReceivedDamagePercentMultiplierWeapon,
    CharacterDeboostReceivedDamagePercentMultiplierWeapon,
    CharacterBoostDealtDamagePercentMultiplierSpells,
    CharacterDeboostDealtDamagePercentMultiplierSpells,
    CharacterBoostReceivedDamagePercentMultiplierSpells,
    CharacterDeboostReceivedDamagePercentMultiplierSpells,
    BoostCharacConvert,
    BuyInBidHouse,
    HomeMade,
    EvolutiveObjectExperience,
    SuperfoodExperience,
    EvolutivePetLevel,
    CharacterLifePointsLostFromBestElement,
    CharacterPlayEmoticon,
    BoostAllSpellBaseDmg,
    PreventFutureSmithmagic,
    SmithmagicForceWeight,
    SmithmagicForceProbability,
    CharacterLifePointsStealFromBestElement,
    FightSplashRawTakenDamageBestElement,
    FightSplashFinalTakenDamageBestElement,
    Wipwipwip,
    CharacterLifePointsLostFromWorstElement,
    ItemExpiration,
    CharacterBoostStrengthPercent,
    CharacterDeboostStrengthPercent,
    CharacterBoostAgilityPercent,
    CharacterDeboostAgilityPercent,
    CharacterBoostIntelligencePercent,
    CharacterDeboostIntelligencePercent,
    CharacterBoostChancePercent,
    CharacterDeboostChancePercent,
    CharacterBoostWisdomPercent,
    CharacterDeboostWisdomPercent,
    CharacterBoostVitalityPercent,
    CharacterDeboostVitalityPercent,
    CharacterBoostActionPointsPercent,
    CharacterDeboostActionPointsPercent,
    CharacterBoostMovementPointsPercent,
    CharacterDeboostMovementPointsPercent,
    CharacterBoostTakleBlockPercent,
    CharacterDeboostTakleBlockPercent,
    CharacterBoostTakleEvadePercent,
    CharacterDeboostTakleEvadePercent,
    CharacterBoostActionPointsLostDodgePercent,
    CharacterDeboostActionPointsLostDodgePercent,
    CharacterBoostMovementPointsLostDodgePercent,
    CharacterDeboostMovementPointsLostDodgePercent,
    CharacterBoostApAttackPercent,
    CharacterDeboostApAttackPercent,
    CharacterBoostMpAttackPercent,
    CharacterDeboostMpAttackPercent,
    LegendaryStatus,
    LegendaryPowerSpell = 2864,
    CharacterGainXpWoBoost,
    CharacterBoostXpCoeff = 2867,
    CharacterAddScalePercent,
    CharacterBoostJobXpCoeff,
    CharacterLowerScalePercent = 2871,
    CharacterBoostThreshold,
    BreachResetRoomSeed,
    BreachResetRoomChallenge,
    CharacterLearnSpellForgettable,
    FightValidateChallenge,
    FightInvalidateChallenge,
    GainLevel,
    CharacterInventoryAddPerfectItemCheck,
    ItemCustomEffect,
    SelfPiloting,
    DistributeGameaction,
    SetTurnWaitingTime,
    CharacterSendInformationTextToMap,
    CharacterSendInformationTextToSubarea,
    CharacterSendInformationTextToArea,
    CharacterSendInformationTextToWorld,
    Unknown,
    CharacterOpenGuildStorage,
    CharacterLifePointsStealFromWorstElement,
    FightSplashFinalTakenDamageWorstElement,
    CharacterAddAlteration,
    CharacterRemoveAlteration,
    CharacterSpeedMultiplier,
    ItemTeleportGroupToMe,
    FightSplashRawTakenDamageWorstElement,
    CharacterLimitStats,
    MultiplyVictoryPointsAva,
    MultiplyDefeatPointsAva,
    SeeAlliesRoleAva,
    SeeOpponentRoleAva,
    TeamPointsLostAva,
    StorePointsAva,
    SpendPointsAva,
    SetSpellRangeMax,
    SetSpellRangeMin,
    AddPrismCristal,
    BoostPortalFreeCellOff,
    BoostPortalProjectionOn,
    BoostPortalProjectionOff,
    BoostPortalFreeCellOn,
    SetSpellApCost = 2913,
    DisableSpellRangeable,
    EnableSpellNolineofsight,
    SetSpellMaxpertarget,
    DeboostSpellMaxpertarget,
    SetSpellMaxperturn,
    DeboostSpellMaxperturn,
    BoostSpellCastGlobalIntvl,
    DeboostSpellCastGlobalIntvl,
    SetSpellCastGlobalIntvl,
    BoostSpellMaxStack,
    DeboostSpellMaxStack,
    SetSpellMaxStack,
    DeboostSpellCriticalHit,
    SetSpellCriticalHit,
    DeboostSpellHeal,
    SetSpellHeal,
    DeboostSpellDmg,
    SetSpellDmg,
    EnableSpellCastoutline,
    DisableSpellCastoutdiagonal,
    EnableSpellCastoutdiagonal,
    BoostSpellBaseHeal,
    CasterExecuteSpellOnCell = 2960,
    CharacterBoostDealtHealPercentMultiplier = 2971,
    CharacterDeboostDealtHealPercentMultiplier,
    FightCasterSplashHeal,
    FightSplashRawInflictedDamageAir,
    FightSplashRawInflictedDamageWater,
    FightSplashRawInflictedDamageFire,
    FightSplashRawInflictedDamageEarth,
    FightSplashRawInflictedDamageNeutral,
    FightSplashRawInflictedDamageBestElement,
    FightSplashRawInflictedDamageWorstElement,
    FightSplashRawInflictedDamage,
    FightSplashFinalInflictedDamageAir,
    FightSplashFinalInflictedDamageWater,
    FightSplashFinalInflictedDamageFire,
    FightSplashFinalInflictedDamageEarth,
    FightSplashFinalInflictedDamageNeutral,
    FightSplashFinalInflictedDamageBestElement,
    FightSplashFinalInflictedDamageWorstElement,
    FightSplashFinalInflictedDamage,
    CharacterReduceMaximumSummonedCreatures,
    LockPrismModule,
    CharacterReadGuide,
    CharacterRenameInvalidAlliance,
    ReducePrismDurabilityReduction,
    TeamPointsWinAva,
    DurationHour,
    CharacterLearnSpellTemporaryMutant,
    CharacterLifePointsWinFromWater,
    CharacterLifePointsWinFromAir,
    CharacterLifePointsWinFromEarth,
    CharacterLifePointsWinFromNeutral,
    CharacterLifePointsWinFromBestElement,
    RefreshMarkQuest,
    InventoryRemoveItem,
    CharacterLeaveGuild,
    CharacterLifePointsWinFromWorstElement,
    StartDialogWithNpc,
    CharacterTriggerChoice,
    PlayAnimationOnMap,
    PlayAnimationOnNpc,
    PlaySpellScriptOnNpc,
    PlayEmoteOnNpc,
    ExecuteSpellScriptUsage = 3792,
    K = 1129
}