using System.Collections.Immutable;
using System.Text;
using Bubble.SourceGenerators.Database.Models;
using Bubble.SourceGenerators.Infrastructure;
using Bubble.SourceGenerators.Infrastructure.Extensions;
using Microsoft.CodeAnalysis;

namespace Bubble.SourceGenerators.Database;

public sealed partial class DatabaseSourceGenerator
{
    private static void Generate(SourceProductionContext context, ImmutableArray<DbTable> tables, string assemblyName, bool isEnabled)
    {
        if (!isEnabled)
            return;

        if (tables.IsEmpty)
            return;

        GeneratePartialClasses(context, tables);
        GenerateDbConnectionAccessorExtensions(context, assemblyName, tables);
    }

    private static void GenerateDbConnectionAccessorExtensions(SourceProductionContext context, string assemblyName, ImmutableArray<DbTable> tables)
    {
        var imports = tables
            .Select(x => x.Namespace)
            .Concat([
                "Bubble.Core.Database",
                "System.Collections.Frozen"
            ])
            .Distinct()
            .OrderBy(x => x)
            .ToList();

        var builder = new StringBuilder()
            .AppendLine("#nullable enable")
            .AppendLine();
        
        var prefix = assemblyName.Split(['.'], StringSplitOptions.RemoveEmptyEntries).Last().Replace("Server", string.Empty);

        imports.ForEach(x => builder.AppendLine($"using {x};"));

        builder
            .AppendLine()
            .AppendLine($"namespace {prefix};")
            .AppendLine()
            .AppendLine("public static class DbConnectionAccessorExtensions")
            .AppendLine("{");

        GenerateDbTypes(builder, tables.ToArray());

        builder
            .AppendLine("}");

        context.AddSource("DbConnectionAccessorExtensions.g.cs", builder.ToString());
    }

    private static void GenerateDbTypes(StringBuilder builder, DbTable[] tables)
    {
        builder
            .AppendLine("\tpublic static Dictionary<Type, (DatabaseTypes DbType, string DbName)> GetDbTypes()")
            .AppendLine("\t{")
            .AppendLine("\t\treturn new Dictionary<Type, (DatabaseTypes DbType, string DbName)>")
            .AppendLine("\t\t{");

        foreach (var table in tables)
        {
            var comma = table == tables.Last() ? string.Empty : ",";

            builder.AppendLine($"\t\t\t[typeof({table.Name})] = (DatabaseTypes.{table.DbType}, \"{table.DbName}\"){comma}");
        }

        builder
            .AppendLine("\t\t};")
            .AppendLine("\t}");
    }


    private static void GenerateInsertSql(SourceWriter writer, DbTable table)
    {
        var columns = table.Columns.Where(x => !x.IsAutoGenerated).ToList();

        writer.AppendIndentedLine("public string GetInsertSql()");

        using (writer.CreateScope())
            writer
                .AppendIndentedLine("const string sql = \"INSERT INTO {0} ({1}) VALUES ({2})\";", table.DbName, string.Join(", ", columns.Select(x => x.DbName)),
                    string.Join(", ", columns.Select(x => $"@{x.Name}")))
                .AppendIndentedLine("return sql;");
    }

    private static void GeneratePartialClasses(SourceProductionContext context, ImmutableArray<DbTable> tables)
    {
        foreach (var table in tables)
        {
            var autoGenName = table.Columns.FirstOrDefault(x => x.IsAutoGenerated)?.Name ?? "Id";
            var autoGenDbName = table.Columns.FirstOrDefault(x => x.IsAutoGenerated)?.DbName;
            var autoGenDbType = table.Columns.FirstOrDefault(x => x.IsAutoGenerated)?.FullType ?? "int";

            var seqName = table.SequenceName ?? $"{table.DbName}_{autoGenDbName ?? "id"}_seq";

            var writer = new SourceWriter()
                .AppendLine("using Bubble.Core.Database;")
                .AppendLine("using Bubble.Core.Database.Attributes;")
                .AppendLine("using InfiniteEnumFlags;")
                .AppendLine("using Npgsql;")
                .AppendLine("using System.Text;")
                .AppendLine()
                .AppendLine("namespace {0};", table.Namespace)
                .AppendLine()
                .AppendLine("public partial class {0} : IEntityRecord<{0}>", table.Name);

            using (writer.CreateScope())
            {
                writer
                    .AppendIndentedLine("public static string TableName => \"{0}\";", table.DbName)
                    .AppendLine()
                    .AppendIndentedLine("public static string AutoGeneratedField => \"{0}\";", autoGenDbName ?? string.Empty)
                    .AppendLine()
                    .AppendIndentedLine("public static bool HasAutoGeneratedField => {0};", autoGenDbName is not null ? "true" : "false")
                    .AppendLine()
                    .AppendIndentedLine("public static string SequenceName => \"{0}\";", seqName)
                    .AppendLine()
                    .AppendIndentedLine("public static DatabaseTypes DatabaseType => DatabaseTypes.{0};", table.DbType)
                    .AppendLine()
                    .AppendIndentedLine("public Flag<{0}Flags> DirtyFlags = {0}Flags.None;", table.Name)
                    .AppendLine()
                    .AppendIndentedLine("public bool MustBeDeleted { get; set; }")
                    .AppendLine()
                    .AppendIndentedLine("public bool IsNew { get; set; }")
                    .AppendLine()
                    .AppendIndentedLine("public {0}()", table.Name)
                    .AppendIndentedLine('{')
                    .AppendIndentedLine('}')
                    .AppendLine();

                var ctorWriter = new SourceWriter();

                foreach (var column in table.Columns)
                {
                    ctorWriter.Append("{0}{1} {2}", column.FullType, column is { IsValueType: true, IsNullable: true } ? "?" : string.Empty, column.Name.ToCamelCase());

                    if (column != table.Columns.Last())
                        ctorWriter.Append(", ");
                }

                writer.AppendIndentedLine("public {0}({1})", table.Name, ctorWriter);

                using (writer.CreateScope())
                    foreach (var column in table.Columns)
                        writer.AppendIndentedLine("{0} = {1};", column.Name, column.Name.ToCamelCase());

                writer
                    .AppendLine()
                    .AppendIndentedLine("public static {0} Create({0}Parameters parameters)", table.Name);

                using (writer.CreateScope())
                {
                    writer.AppendIndented("return new {0}(", table.Name);

                    foreach (var column in table.Columns)
                        writer.Append("{0}{1}", column.IsAutoGenerated ? "0" : $"parameters.{column.Name}", column != table.Columns.Last() ? ", " : string.Empty);

                    writer.AppendLine(") { IsNew = true };");
                }

                writer.AppendIndentedLine("public void SetAutoGeneratedKey(object? key)");

                using (writer.CreateScope())
                    if (autoGenDbName is null)
                        writer.AppendIndentedLine("throw new InvalidOperationException(\"AutoGeneratedField is not defined.\");");
                    else
                    {
                        writer.AppendIndentedLine("if (key is not null)");

                        using (writer.CreateScope())
                            writer.AppendIndentedLine("{0} = ({1})key;", autoGenName, autoGenDbType);
                    }

                writer
                    .AppendLine()
                    .AppendIndentedLine("public object GetAutoGeneratedKey()");

                using (writer.CreateScope())
                    if (autoGenDbName is null)
                        writer.AppendIndentedLine("throw new InvalidOperationException(\"AutoGeneratedField is not defined.\");");
                    else
                        writer.AppendIndentedLine("return {0};", autoGenName);

                writer.AppendLine();

                foreach (var column in table.Columns)
                {
                    writer.AppendIndentedLine("public void Set{0}({1} value)", column.Name, column.FullType);

                    using (writer.CreateScope())
                        writer
                            .AppendIndentedLine("if ({0} == value)", column.Name)
                            .Indent()
                            .AppendIndentedLine("return;")
                            .Unindent()
                            .AppendLine()
                            .AppendIndentedLine("{0} = value;", column.Name)
                            .AppendIndentedLine("DirtyFlags = DirtyFlags.SetFlag({0}Flags.{1});", table.Name, column.Name);

                    writer.AppendLine();
                }

                writer.AppendIndentedLine("public bool IsDirty()");

                using (writer.CreateScope())
                    writer.AppendIndentedLine("return DirtyFlags != {0}Flags.None;", table.Name);

                writer
                    .AppendLine()
                    .AppendIndentedLine("public void ResetDirty()");

                using (writer.CreateScope())
                    writer.AppendIndentedLine("DirtyFlags = {0}Flags.None;", table.Name);

                writer
                    .AppendLine()
                    .AppendIndentedLine("public NpgsqlParameter[] GetParameters()");

                using (writer.CreateScope())
                {
                    writer
                        .AppendIndentedLine("return new NpgsqlParameter[]")
                        .AppendIndentedLine('{')
                        .Indent();

                    foreach (var column in table.Columns)
                    {
                        var comma = column.Equals(table.Columns.Last()) ? string.Empty : ",";

                        var assignation = column.IsNullable
                            ? $"new NpgsqlParameter(nameof({table.Name}.{column.Name}), {column.Name} is null ? DBNull.Value : {column.Name}) {{ IsNullable = true }}{comma}"
                            : $"new NpgsqlParameter<{column.FullType}>(nameof({table.Name}.{column.Name}), {column.Name}){comma}";

                        writer.AppendIndentedLine("{0}", assignation);
                    }

                    writer
                        .Unindent()
                        .AppendIndentedLine("};");
                }

                writer
                    .AppendLine()
                    .AppendIndentedLine("public static {0} Map(NpgsqlDataReader reader)", table.Name);

                using (writer.CreateScope())
                {
                    foreach (var column in table.Columns)
                    {
                        var assignation = column.IsNullable
                            ? $"reader.IsDBNull(reader.GetOrdinal(\"{column.DbName}\")) ? null : reader.GetFieldValue<{column.FullType}{(column.IsValueType ? "?" : string.Empty)}>(reader.GetOrdinal(\"{column.DbName}\"))"
                            : $"reader.GetFieldValue<{column.FullType}>(reader.GetOrdinal(\"{column.DbName}\"))";

                        writer.AppendIndentedLine("var {0} = {1};", column.VariableName, assignation);
                    }

                    writer
                        .AppendLine()
                        .AppendIndented("return new {0}(", table.Name);

                    foreach (var column in table.Columns)
                    {
                        writer.Append(column.VariableName);

                        if (column != table.Columns.Last())
                            writer.Append(", ");
                    }

                    writer
                        .AppendLine(");");
                }

                writer.AppendLine();
                GenerateInsertSql(writer, table);
                writer.AppendLine();
                GenerateUpdateSql(writer, table);
                writer.AppendLine();
                GenerateRemoveSql(writer, table);
            }

            writer
                .AppendLine()
                .AppendLine("public sealed class {0}Flags : InfiniteEnum<{0}Flags>", table.Name);

            using (writer.CreateScope())
            {
                writer
                    .AppendIndentedLine("public static readonly Flag<{0}Flags> None = new(-1);", table.Name)
                    .AppendLine();

                var i = 0;

                foreach (var column in table.Columns)
                {
                    writer.AppendIndentedLine("public static readonly Flag<{0}Flags> {1} = new({2});", table.Name, column.Name, i);

                    if (column != table.Columns.Last())
                        writer.AppendLine();

                    i++;
                }
            }

            writer
                .AppendLine()
                .AppendLine("public struct {0}Parameters", table.Name);

            using (writer.CreateScope())
                foreach (var column in table.Columns)
                {
                    if (column.IsAutoGenerated)
                        continue;

                    writer.AppendIndentedLine("public required {0}{1} {2} {{ get; set; }}", column.FullType, column.IsNullable ? "?" : string.Empty, column.Name);

                    if (column != table.Columns.Last())
                        writer.AppendLine();
                }

            context.AddSource($"{table.Name}.g.cs", writer.ToSourceText());
        }
    }

    private static void GenerateRemoveSql(SourceWriter writer, DbTable table)
    {
        var autoGenName = table.Columns.FirstOrDefault(x => x.IsAutoGenerated)?.Name ?? "Id";
        var autoGenDbName = table.Columns.FirstOrDefault(x => x.IsAutoGenerated)?.DbName ?? "id";

        writer.AppendIndentedLine("public string GetRemoveSql()");

        using (writer.CreateScope())
            writer
                .AppendIndentedLine("const string sql = \"DELETE FROM {0} WHERE {1}=@{2}\";", table.DbName, autoGenDbName, autoGenName)
                .AppendIndentedLine("return sql;");
    }

    private static void GenerateUpdateSql(SourceWriter writer, DbTable table)
    {
        writer.AppendIndentedLine("public string GetUpdateSql()");

        using (writer.CreateScope())
        {
            writer
                .AppendIndentedLine("var builder = new StringBuilder(\"UPDATE {0} SET \");", table.DbName)
                .AppendLine();

            foreach (var column in table.Columns)
            {
                if (column.IsAutoGenerated)
                    continue;

                writer.AppendIndentedLine("if (DirtyFlags.HasFlag({0}Flags.{1}))", table.Name, column.Name);

                using (writer.CreateScope())
                    writer.AppendIndentedLine("builder.Append(\"\\\"{0}\\\" = @{1}, \");", column.DbName, column.Name);

                writer.AppendLine();
            }

            var autoGenName = table.Columns.FirstOrDefault(x => x.IsAutoGenerated)?.Name ?? "Id";
            var autoGenDbName = table.Columns.FirstOrDefault(x => x.IsAutoGenerated)?.DbName ?? "id";

            writer.AppendIndentedLine("if (DirtyFlags != {0}Flags.None)", table.Name);

            using (writer.CreateScope())
                writer
                    .AppendIndentedLine("builder.Remove(builder.Length - 2, 2);")
                    .AppendLine();

            writer
                .AppendIndentedLine("return builder")
                .Indent()
                .AppendIndentedLine(".Append($\" WHERE {0} = @{1}\")", autoGenDbName, autoGenName)
                .AppendIndentedLine(".ToString();")
                .Unindent();
        }
    }
}