"""
C# code generator: produces OtomAI-compatible message classes from the schema registry.

Generates protobuf-net C# classes that match the Bubble.D3.Bot pattern but are
structured for the OtomAI project (proper namespaces, IProtoMessage interface).
"""

from pathlib import Path
from typing import Optional


HEADER_TEMPLATE = """// <auto-generated>
//   Generated by proto-sync tool — do not edit manually.
//   Source: {source_file} (via {proto_input})
//   Synced: {timestamp}
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
"""

FOOTER_TEMPLATE = """
#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
"""


def generate_message_file(msg: dict, timestamp: str, namespace: Optional[str] = None) -> str:
    """Generate a complete C# file for a message definition."""
    lines = []

    # Header
    lines.append(HEADER_TEMPLATE.format(
        source_file=msg.get("source_file", "unknown"),
        proto_input=msg.get("proto_input", "unknown"),
        timestamp=timestamp,
    ))

    if namespace:
        lines.append(f"namespace {namespace};")
        lines.append("")

    # Main class
    lines.append(_generate_class(msg, indent=0))

    # Footer
    lines.append(FOOTER_TEMPLATE)

    return "\n".join(lines)


def _generate_class(msg: dict, indent: int) -> str:
    """Generate a single class definition."""
    pad = "    " * indent
    lines = []

    lines.append(f"{pad}[global::ProtoBuf.ProtoContract()]")
    lines.append(f"{pad}public partial class {msg['class_name']} : global::ProtoBuf.IExtensible, IProtoMessage")
    lines.append(f"{pad}{{")

    # TypeUrl
    lines.append(f'{pad}    public static string TypeUrl => "{msg["type_url"]}";')

    # Extension data
    lines.append(f"{pad}    private global::ProtoBuf.IExtension __pbn__extensionData;")
    lines.append(f"{pad}    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)")
    lines.append(f"{pad}        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);")
    lines.append("")

    # Track oneof groups for DiscriminatedUnion fields
    oneof_groups = set()

    # Regular fields (non-oneof)
    for f in msg.get("fields", []):
        if f.get("is_oneof"):
            continue

        # Default value attribute
        if f.get("default_value") is not None:
            lines.append(f'{pad}    [global::System.ComponentModel.DefaultValue("{f["default_value"]}")]')

        # ProtoMember attribute
        lines.append(f'{pad}    [global::ProtoBuf.ProtoMember({f["number"]}, Name = @"{f["proto_name"]}")]')

        # Property
        req = "required " if f.get("required") else ""
        ctype = f["csharp_type"]

        if f.get("is_list"):
            full_type = f"global::System.Collections.Generic.List<{ctype.replace('List<', '').rstrip('>')}>"
            lines.append(f"{pad}    public {req}{full_type} {f['csharp_name']} {{ get; set; }} = new {full_type}();")
        else:
            default = ""
            if f.get("default_value") is not None:
                default = f' = "{f["default_value"]}";'
            elif not f.get("required") and ctype == "string":
                default = ' = "";'

            lines.append(f"{pad}    public {req}{ctype} {f['csharp_name']} {{ get; set; }}{default}")
        lines.append("")

    # Oneof fields
    for f in msg.get("fields", []):
        if not f.get("is_oneof"):
            continue

        group = f.get("oneof_group", "")
        disc = f.get("oneof_discriminator", 0)

        lines.append(f'{pad}    [global::ProtoBuf.ProtoMember({f["number"]}, Name = @"{f["proto_name"]}")]')
        lines.append(f"{pad}    public {f['csharp_type']} {f['csharp_name']}")
        lines.append(f"{pad}    {{")
        lines.append(f"{pad}        get => __pbn__{group}.Is({disc}) ? (({f['csharp_type']})__pbn__{group}.Object) : default;")
        lines.append(f"{pad}        set => __pbn__{group} = new global::ProtoBuf.DiscriminatedUnionObject({disc}, value);")
        lines.append(f"{pad}    }}")
        lines.append(f"{pad}    public bool ShouldSerialize{f['csharp_name']}() => __pbn__{group}.Is({disc});")
        lines.append(f"{pad}    public void Reset{f['csharp_name']}() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__{group}, {disc});")
        lines.append("")
        oneof_groups.add(group)

    # Oneof backing fields
    for group in sorted(oneof_groups):
        lines.append(f"{pad}    private global::ProtoBuf.DiscriminatedUnionObject __pbn__{group};")
        lines.append("")

    # Enums
    for enum_def in msg.get("enums", []):
        lines.append(f'{pad}    [global::ProtoBuf.ProtoContract(Name = @"{enum_def["proto_name"]}")]')
        lines.append(f'{pad}    public enum {enum_def["name"]}')
        lines.append(f"{pad}    {{")
        for ev in enum_def.get("values", []):
            lines.append(f'{pad}        [global::ProtoBuf.ProtoEnum(Name = @"{ev["proto_name"]}")]')
            lines.append(f'{pad}        {ev["name"]} = {ev["number"]},')
        lines.append(f"{pad}    }}")
        lines.append("")

    # Nested messages
    for nested in msg.get("nested_messages", []):
        lines.append(_generate_class(nested, indent + 1))
        lines.append("")

    lines.append(f"{pad}}}")

    return "\n".join(lines)


def generate_all(messages: dict[str, dict], output_dir: Path, timestamp: str,
                 namespace: Optional[str] = None):
    """Generate C# files for all messages in a snapshot."""
    output_dir.mkdir(parents=True, exist_ok=True)

    generated = []
    for type_url, msg in sorted(messages.items()):
        # Skip internal types (TypeUrl starting with ".")
        if type_url.startswith("."):
            continue

        filename = f"{msg['source_file']}"
        filepath = output_dir / filename
        content = generate_message_file(msg, timestamp, namespace)
        filepath.write_text(content, encoding="utf-8")
        generated.append(filepath)

    return generated


def generate_mappings(messages: dict[str, dict]) -> dict[str, str]:
    """Generate a game_mappings.json dict from the schema."""
    mappings = {}
    for type_url, msg in sorted(messages.items()):
        if not type_url.startswith("."):
            mappings[type_url] = msg["class_name"]
    return mappings
