// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hdo.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class TreasureHuntEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hdo";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"start_map_id")]
    public required long StartMapId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"flags")]
    public required global::System.Collections.Generic.List<TreasureHuntFlag> Flags { get; set; } = new global::System.Collections.Generic.List<TreasureHuntFlag>();

    [global::ProtoBuf.ProtoMember(3, Name = @"current_check_point")]
    public required int CurrentCheckPoint { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"total_check_point")]
    public required int TotalCheckPoint { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"available_retry_count")]
    public required int AvailableRetryCount { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"known_steps")]
    public required global::System.Collections.Generic.List<TreasureHuntStep> KnownSteps { get; set; } = new global::System.Collections.Generic.List<TreasureHuntStep>();

    [global::ProtoBuf.ProtoMember(7, Name = @"quest_type")]
    public required TreasureHuntType QuestType { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"total_step_count")]
    public required int TotalStepCount { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public partial class TreasureHuntFlag : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".TreasureHuntFlag";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dzoo")]
        public required FlagState Dzoo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"map_id")]
        public required long MapId { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum FlagState
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"OK")]
            Ok = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"WRONG")]
            Wrong = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TreasureHuntStep : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".TreasureHuntStep";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"dzod")]
        [global::System.ComponentModel.DefaultValue("")]
        public required string Dzod { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"dzoe")]
        public required Hdh Dzoe { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"fight")]
        public Hdh Fight
        {
            get => __pbn__step.Is(1) ? ((Hdh)__pbn__step.Object) : default;
            set => __pbn__step = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeFight() => __pbn__step.Is(1);
        public void ResetFight() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__step, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__step;

        [global::ProtoBuf.ProtoMember(3, Name = @"follow_direction_to_poi")]
        public Hdd FollowDirectionToPoi
        {
            get => __pbn__step.Is(3) ? ((Hdd)__pbn__step.Object) : default;
            set => __pbn__step = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeFollowDirectionToPoi() => __pbn__step.Is(3);
        public void ResetFollowDirectionToPoi() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__step, 3);

        [global::ProtoBuf.ProtoMember(5, Name = @"follow_direction")]
        public Hdf FollowDirection
        {
            get => __pbn__step.Is(5) ? ((Hdf)__pbn__step.Object) : default;
            set => __pbn__step = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeFollowDirection() => __pbn__step.Is(5);
        public void ResetFollowDirection() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__step, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"dig")]
        public Hdg Dig
        {
            get => __pbn__step.Is(6) ? ((Hdg)__pbn__step.Object) : default;
            set => __pbn__step = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
        }
        public bool ShouldSerializeDig() => __pbn__step.Is(6);
        public void ResetDig() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__step, 6);

        [global::ProtoBuf.ProtoMember(7, Name = @"follow_direction_to_hint")]
        public Hde FollowDirectionToHint
        {
            get => __pbn__step.Is(7) ? ((Hde)__pbn__step.Object) : default;
            set => __pbn__step = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
        }
        public bool ShouldSerializeFollowDirectionToHint() => __pbn__step.Is(7);
        public void ResetFollowDirectionToHint() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__step, 7);

        public StepOneofCase StepCase => (StepOneofCase)__pbn__step.Discriminator;

        public enum StepOneofCase
        {
            None = 0,
            Fight = 1,
            FollowDirectionToPoi = 3,
            FollowDirection = 5,
            Dig = 6,
            FollowDirectionToHint = 7,
        }

        [global::ProtoBuf.ProtoContract(Name = @"hdh")]
        public partial class Hdh : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".hdh";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract(Name = @"hdd")]
        public partial class Hdd : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".hdd";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"direction")]
            public required Jdg Direction { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"poi_label_id")]
            public required int PoiLabelId { get; set; }

        }

        [global::ProtoBuf.ProtoContract(Name = @"hdf")]
        public partial class Hdf : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".hdf";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"map_count")]
            public required int MapCount { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"direction")]
            public required Jdg Direction { get; set; }

        }

        [global::ProtoBuf.ProtoContract(Name = @"hdg")]
        public partial class Hdg : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".hdg";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract(Name = @"hde")]
        public partial class Hde : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".hde";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"npc_id")]
            public required int NpcId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"direction")]
            public required Jdg Direction { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
