// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hdv.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class TreasureHuntAnswerEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hdv";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"quest_type")]
    public required TreasureHuntType QuestType { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"result")]
    public required Result ResultValue { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public enum Result
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_UNDEFINED")]
        ErrorUndefined = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_NO_QUEST_FOUND")]
        ErrorNoQuestFound = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_ALREADY_HAVE_QUEST")]
        ErrorAlreadyHaveQuest = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_NOT_AVAILABLE")]
        ErrorNotAvailable = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ERROR_DAILY_LIMIT_EXCEEDED")]
        ErrorDailyLimitExceeded = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"OK")]
        Ok = 5,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
