// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hfa.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class TeleportToBuddyClosedEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hfa";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dzui")]
    public required long Dzui { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"dzuj")]
    public required int Dzuj { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"dzuk")]
    public long Dzuk
    {
        get => __pbn__Dzuk.GetValueOrDefault();
        set => __pbn__Dzuk = value;
    }
    public bool ShouldSerializeDzuk() => __pbn__Dzuk != null;
    public void ResetDzuk() => __pbn__Dzuk = null;
    private long? __pbn__Dzuk;

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
