// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hfc.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class GroupTeleportPlayerOfferEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hfc";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dzut")]
    public required int Dzut { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"dzuu")]
    public required int Dzuu { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"dzuv")]
    public required long Dzuv { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"dzuw")]
    public required int Dzuw { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"dzux")]
    public required long Dzux { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"dzuy")]
    public required int Dzuy { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"dzuz")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Dzuz { get; set; } = "";

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
