// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hfi.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class TeleportPlayerClosedEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hfi";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dzwd")]
    public bool Dzwd
    {
        get => __pbn__Dzwd.GetValueOrDefault();
        set => __pbn__Dzwd = value;
    }
    public bool ShouldSerializeDzwd() => __pbn__Dzwd != null;
    public void ResetDzwd() => __pbn__Dzwd = null;
    private bool? __pbn__Dzwd;

    [global::ProtoBuf.ProtoMember(2, Name = @"dzwf")]
    public required long Dzwf { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"dzwg")]
    public required long Dzwg { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
