// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hfn.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class TaxCollectorOrderedSpellUpdatedEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hfn";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"dzxf")]
    public required global::System.Collections.Generic.List<TaxCollectorOrderedSpell> Dzxfs { get; set; } = new global::System.Collections.Generic.List<TaxCollectorOrderedSpell>();

    [global::ProtoBuf.ProtoMember(2, Name = @"dzxg")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Dzxg { get; set; } = "";

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
