// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hhi.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class MimicryResponse : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hhi";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eaev")]
    public required Hhf Eaev { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"eaew")]
    public int Eaew
    {
        get => __pbn__Eaew.GetValueOrDefault();
        set => __pbn__Eaew = value;
    }
    public bool ShouldSerializeEaew() => __pbn__Eaew != null;
    public void ResetEaew() => __pbn__Eaew = null;
    private int? __pbn__Eaew;

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
