// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hiq.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PlayersMapAttackableStatusUpdateEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hiq";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eakf")]
    public required global::System.Collections.Generic.List<Hio> Eakfs { get; set; } = new global::System.Collections.Generic.List<Hio>();

    [global::ProtoBuf.ProtoContract(Name = @"hio")]
    public partial class Hio : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".hio";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eajv")]
        public required long Eajv { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"eajw")]
        public required long Eajw { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"eajx")]
        public required Jcu Eajx { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"eajy")]
        public required int Eajy { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"eajz")]
        public int Eajz
        {
            get => __pbn__Eajz.GetValueOrDefault();
            set => __pbn__Eajz = value;
        }
        public bool ShouldSerializeEajz() => __pbn__Eajz != null;
        public void ResetEajz() => __pbn__Eajz = null;
        private int? __pbn__Eajz;

        [global::ProtoBuf.ProtoMember(6, Name = @"eakb", IsPacked = true)]
        public required global::System.Collections.Generic.List<bool> Eakbs { get; set; } = new global::System.Collections.Generic.List<bool>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
