// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hiy.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class SetMoodEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hiy";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ealf")]
    public required int Ealf { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ealg")]
    public required Hiw Ealg { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"hiw")]
    public enum Hiw
    {
        [global::ProtoBuf.ProtoEnum(Name = @"HIW_DEWI")]
        HiwDewi = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"HIW_DEWJ")]
        HiwDewj = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"HIW_DEWK")]
        HiwDewk = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
