// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hjc.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class SpouseInformationEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hjc";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ealw")]
    public required int Ealw { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ealx")]
    public required int Ealx { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ealy")]
    public required AllianceInformation Ealy { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ealz")]
    public required GuildInformation Ealz { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"eama")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Eama { get; set; } = "";

    [global::ProtoBuf.ProtoMember(6, Name = @"eamb")]
    public required Hja Eamb { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"eamc")]
    public required Gender Eamc { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"eamd")]
    public required EntityLook Eamd { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"eame")]
    public required long Eame { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"eamf")]
    public required Jcr Eamf { get; set; }

    [global::ProtoBuf.ProtoMember(11, Name = @"eamg")]
    public required long Eamg { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"hja")]
    public partial class Hja : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".hja";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ealo")]
        public required bool Ealo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ealp")]
        public required bool Ealp { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ealq")]
        public required long Ealq { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ealr")]
        public required int Ealr { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"eals")]
        public required int Eals { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
