// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hjq.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ServerSettingsEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hjq";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eanz")]
    public required Jdl Eanz { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"eaoa")]
    public required bool Eaoa { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"eaob")]
    public required int Eaob { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"eaoc")]
    public required int Eaoc { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"eaod")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Eaod { get; set; } = "";

    [global::ProtoBuf.ProtoMember(6, Name = @"eaoe")]
    public required int Eaoe { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
