// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hke.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PlayerFightFriendlyRequestedEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hke";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"fight_id")]
    public required int FightId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"fight_id2")]
    public required int FightId2 { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"source_id")]
    public required long SourceId { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"target_id")]
    public required long TargetId { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
