// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hkm.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class DelayedActionEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hkm";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"easb")]
    public required Jcm Easb { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"easc")]
    public int Easc
    {
        get => __pbn__Easc.GetValueOrDefault();
        set => __pbn__Easc = value;
    }
    public bool ShouldSerializeEasc() => __pbn__Easc != null;
    public void ResetEasc() => __pbn__Easc = null;
    private int? __pbn__Easc;

    [global::ProtoBuf.ProtoMember(3, Name = @"ease")]
    public required long Ease { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"easf")]
    public required long Easf { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
