// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hlc.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class QuestActive : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hlc";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eauc")]
    public required Hla Eauc { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"eaud")]
    public required int Eaud { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"hla")]
    public partial class Hla : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".hla";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eatx")]
        public required int Eatx { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"eaty")]
        public required global::System.Collections.Generic.List<QuestObjective> Eaties { get; set; } = new global::System.Collections.Generic.List<QuestObjective>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
