// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hlj.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class QuestsFollowedOrderRefreshRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hlj";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eavo", IsPacked = true)]
    public required global::System.Collections.Generic.List<int> Eavoes { get; set; } = new global::System.Collections.Generic.List<int>();

    [global::ProtoBuf.ProtoMember(2, Name = @"eavp")]
    public int Eavp
    {
        get => __pbn__Eavp.GetValueOrDefault();
        set => __pbn__Eavp = value;
    }
    public bool ShouldSerializeEavp() => __pbn__Eavp != null;
    public void ResetEavp() => __pbn__Eavp = null;
    private int? __pbn__Eavp;

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
