// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hmh.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PrismAttackResultEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hmh";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eaza")]
    public required Hmf Eaza { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"eazb")]
    public long Eazb
    {
        get => __pbn__Eazb.GetValueOrDefault();
        set => __pbn__Eazb = value;
    }
    public bool ShouldSerializeEazb() => __pbn__Eazb != null;
    public void ResetEazb() => __pbn__Eazb = null;
    private long? __pbn__Eazb;

    [global::ProtoBuf.ProtoMember(3, Name = @"eazd")]
    public required PrismLocalizedInformation Eazd { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"hmf")]
    public enum Hmf
    {
        [global::ProtoBuf.ProtoEnum(Name = @"HMF_DFOS")]
        HmfDfos = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"HMF_DFOT")]
        HmfDfot = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
