// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hmn.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PresetOutfitUpdateRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hmn";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ebab")]
    public required int Ebab { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ebac")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ebac { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"ebad")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Ebad
    {
        get => __pbn__Ebad ?? "";
        set => __pbn__Ebad = value;
    }
    public bool ShouldSerializeEbad() => __pbn__Ebad != null;
    public void ResetEbad() => __pbn__Ebad = null;
    private string __pbn__Ebad;

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
