// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hng.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PresetUseResponse : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hng";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ebcr")]
    public Hnd Ebcr
    {
        get => __pbn__ebcu.Is(1) ? ((Hnd)__pbn__ebcu.Int32) : default;
        set => __pbn__ebcu = new global::ProtoBuf.DiscriminatedUnion32Object(1, (int)value);
    }
    public bool ShouldSerializeEbcr() => __pbn__ebcu.Is(1);
    public void ResetEbcr() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__ebcu, 1);

    private global::ProtoBuf.DiscriminatedUnion32Object __pbn__ebcu;

    [global::ProtoBuf.ProtoMember(2, Name = @"ebct")]
    public Hne Ebct
    {
        get => __pbn__ebcu.Is(2) ? ((Hne)__pbn__ebcu.Object) : default;
        set => __pbn__ebcu = new global::ProtoBuf.DiscriminatedUnion32Object(2, value);
    }
    public bool ShouldSerializeEbct() => __pbn__ebcu.Is(2);
    public void ResetEbct() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__ebcu, 2);

    public EbcuOneofCase EbcuCase => (EbcuOneofCase)__pbn__ebcu.Discriminator;

    public enum EbcuOneofCase
    {
        None = 0,
        Ebcr = 1,
        Ebct = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"hne")]
    public partial class Hne : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".hne";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ebcl")]
        public int Ebcl
        {
            get => __pbn__Ebcl.GetValueOrDefault();
            set => __pbn__Ebcl = value;
        }
        public bool ShouldSerializeEbcl() => __pbn__Ebcl != null;
        public void ResetEbcl() => __pbn__Ebcl = null;
        private int? __pbn__Ebcl;

        [global::ProtoBuf.ProtoMember(2, Name = @"ebcn", IsPacked = true)]
        public required global::System.Collections.Generic.List<int> Ebcns { get; set; } = new global::System.Collections.Generic.List<int>();

    }

    [global::ProtoBuf.ProtoContract(Name = @"hnd")]
    public enum Hnd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"HND_DFTH")]
        HndDfth = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"HND_DFTI")]
        HndDfti = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"HND_DFTJ")]
        HndDftj = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"HND_DFTK")]
        HndDftk = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"HND_DFTL")]
        HndDftl = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"HND_DFTM")]
        HndDftm = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"HND_DFTN")]
        HndDftn = 6,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
