// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hoh.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PresetRenameResponse : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hoh";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ebgj")]
    public required Hof Ebgj { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"hof")]
    public enum Hof
    {
        [global::ProtoBuf.ProtoEnum(Name = @"HOF_DFYM")]
        HofDfym = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"HOF_DFYN")]
        HofDfyn = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"HOF_DFYO")]
        HofDfyo = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"HOF_DFYP")]
        HofDfyp = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"HOF_DFYQ")]
        HofDfyq = 4,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
