// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hop.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ForgettableSpellPresetInfo : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hop";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ebhx")]
    public required int Ebhx { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ebhy")]
    public required SpellPreset Ebhy { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ebhz")]
    [global::ProtoBuf.ProtoMap]
    public required global::System.Collections.Generic.Dictionary<int, ForgettableSpellInfo> Ebhzs { get; set; } = new global::System.Collections.Generic.Dictionary<int, ForgettableSpellInfo>();

    [global::ProtoBuf.ProtoMember(4, Name = @"ebia")]
    public required bool Ebia { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ebib")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ebib { get; set; } = "";

    [global::ProtoBuf.ProtoMember(6, Name = @"ebic")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ebic { get; set; } = "";

    [global::ProtoBuf.ProtoMember(7, Name = @"ebid")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ebid { get; set; } = "";

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
