// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hpa.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PresetSpellUpdateRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hpa";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ebkh")]
    public required SpellPreset Ebkh { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ebki")]
    public required Hoy Ebki { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ebkj")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ebkj { get; set; } = "";

    [global::ProtoBuf.ProtoMember(4, Name = @"ebkk")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ebkk { get; set; } = "";

    [global::ProtoBuf.ProtoContract(Name = @"hoy")]
    public enum Hoy
    {
        [global::ProtoBuf.ProtoEnum(Name = @"HOY_DGEE")]
        HoyDgee = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"HOY_DGEF")]
        HoyDgef = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"HOY_DGEG")]
        HoyDgeg = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
