// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hpj.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PresetOrigin : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hpj";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ebln")]
    public Hpf Ebln
    {
        get => __pbn__eblq.Is(1) ? ((Hpf)__pbn__eblq.Object) : default;
        set => __pbn__eblq = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializeEbln() => __pbn__eblq.Is(1);
    public void ResetEbln() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eblq, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__eblq;

    [global::ProtoBuf.ProtoMember(2, Name = @"eblo")]
    public Hph Eblo
    {
        get => __pbn__eblq.Is(2) ? ((Hph)__pbn__eblq.Object) : default;
        set => __pbn__eblq = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeEblo() => __pbn__eblq.Is(2);
    public void ResetEblo() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eblq, 2);

    [global::ProtoBuf.ProtoMember(3, Name = @"eblp")]
    public Hpg Eblp
    {
        get => __pbn__eblq.Is(3) ? ((Hpg)__pbn__eblq.Object) : default;
        set => __pbn__eblq = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
    }
    public bool ShouldSerializeEblp() => __pbn__eblq.Is(3);
    public void ResetEblp() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eblq, 3);

    public EblqOneofCase EblqCase => (EblqOneofCase)__pbn__eblq.Discriminator;

    public enum EblqOneofCase
    {
        None = 0,
        Ebln = 1,
        Eblo = 2,
        Eblp = 3,
    }

    [global::ProtoBuf.ProtoContract(Name = @"hpf")]
    public partial class Hpf : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".hpf";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract(Name = @"hph")]
    public partial class Hph : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".hph";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eblj")]
        [global::System.ComponentModel.DefaultValue("")]
        public required string Eblj { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract(Name = @"hpg")]
    public partial class Hpg : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".hpg";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
