// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hpq.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PartyMemberRemoveEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hpq";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"kicker_id")]
    public long KickerId
    {
        get => __pbn__KickerId.GetValueOrDefault();
        set => __pbn__KickerId = value;
    }
    public bool ShouldSerializeKickerId() => __pbn__KickerId != null;
    public void ResetKickerId() => __pbn__KickerId = null;
    private long? __pbn__KickerId;

    [global::ProtoBuf.ProtoMember(2, Name = @"party_id")]
    public required int PartyId { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"leaving_player_id")]
    public required long LeavingPlayerId { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
