// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hps.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PartyKickRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hps";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ebmw")]
    public bool Ebmw
    {
        get => __pbn__Ebmw.GetValueOrDefault();
        set => __pbn__Ebmw = value;
    }
    public bool ShouldSerializeEbmw() => __pbn__Ebmw != null;
    public void ResetEbmw() => __pbn__Ebmw = null;
    private bool? __pbn__Ebmw;

    [global::ProtoBuf.ProtoMember(2, Name = @"ebmy")]
    public required int Ebmy { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ebmz")]
    public required long Ebmz { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
