// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hpt.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PartyInvitationDetailsEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hpt";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ebnd")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ebnd { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"ebne")]
    public required global::System.Collections.Generic.List<PartyGuest> Ebnes { get; set; } = new global::System.Collections.Generic.List<PartyGuest>();

    [global::ProtoBuf.ProtoMember(3, Name = @"ebnf")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ebnf { get; set; } = "";

    [global::ProtoBuf.ProtoMember(4, Name = @"ebng")]
    public required PartyType Ebng { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ebnh")]
    public required global::System.Collections.Generic.List<Character> Ebnhs { get; set; } = new global::System.Collections.Generic.List<Character>();

    [global::ProtoBuf.ProtoMember(6, Name = @"ebni")]
    public required int Ebni { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"ebnj")]
    public required long Ebnj { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"ebnk")]
    public required long Ebnk { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
