// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hqa.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PartyFollowMemberRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hqa";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ebof")]
    public required long Ebof { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ebog")]
    public bool Ebog
    {
        get => __pbn__Ebog.GetValueOrDefault();
        set => __pbn__Ebog = value;
    }
    public bool ShouldSerializeEbog() => __pbn__Ebog != null;
    public void ResetEbog() => __pbn__Ebog = null;
    private bool? __pbn__Ebog;

    [global::ProtoBuf.ProtoMember(3, Name = @"eboi")]
    public required int Eboi { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
