// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hqi.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PartyGuest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hqi";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ebpr")]
    public required global::System.Collections.Generic.List<PartyEntity> Ebprs { get; set; } = new global::System.Collections.Generic.List<PartyEntity>();

    [global::ProtoBuf.ProtoMember(2, Name = @"ebps")]
    public required long Ebps { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ebpt")]
    public required Gender Ebpt { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ebpu")]
    public required CharacterStatus Ebpu { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ebpv")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ebpv { get; set; } = "";

    [global::ProtoBuf.ProtoMember(6, Name = @"ebpw")]
    public required int Ebpw { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"ebpx")]
    public required EntityLook Ebpx { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"ebpy")]
    public required long Ebpy { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
