// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hql.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class AutoFollowDeactivationResponse : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hql";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ebqc")]
    public required Hqj Ebqc { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ebqd")]
    public required Hqj Ebqd { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"hqj")]
    public enum Hqj
    {
        [global::ProtoBuf.ProtoEnum(Name = @"HQJ_DGMU")]
        HqjDgmu = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"HQJ_DGMV")]
        HqjDgmv = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
