// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hqw.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PartyMemberInFightEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hqw";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"party_id")]
    public required int PartyId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
    public required Hpn Reason { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"member_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string MemberName { get; set; } = "";

    [global::ProtoBuf.ProtoMember(4, Name = @"fight_id")]
    public required int FightId { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"time_before_fight_start")]
    public required int TimeBeforeFightStart { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"member_id")]
    public required long MemberId { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"member_account_id")]
    public required long MemberAccountId { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"standard_fight_map")]
    public required MapExtendedCoordinates StandardFightMap { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
