// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hrq.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PartyInvitationEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hrq";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"party_id")]
    public required int PartyId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"from_player_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string FromPlayerName { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"from_player_id")]
    public required long FromPlayerId { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"party_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string PartyName { get; set; } = "";

    [global::ProtoBuf.ProtoMember(5, Name = @"to_player_id")]
    public required long ToPlayerId { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"party_type")]
    public required PartyType PartyType { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"max_participants")]
    public required int MaxParticipants { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
