// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: htb.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PaddocksToSellEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "htb";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ecbc")]
    public required global::System.Collections.Generic.List<Hsz> Ecbcs { get; set; } = new global::System.Collections.Generic.List<Hsz>();

    [global::ProtoBuf.ProtoMember(2, Name = @"ecbd")]
    public required int Ecbd { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ecbe")]
    public required int Ecbe { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ecbf")]
    public required int Ecbf { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"hsz")]
    public partial class Hsz : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".hsz";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ecat")]
        public required int Ecat { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ecau")]
        public required MapCoordinates Ecau { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ecav")]
        [global::System.ComponentModel.DefaultValue("")]
        public required string Ecav { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"ecaw")]
        public required int Ecaw { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"ecax")]
        public required int Ecax { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"ecay")]
        public required long Ecay { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
