// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: htt.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class NpcDialogReplyRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "htt";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ecdm")]
    public int Ecdm
    {
        get => __pbn__Ecdm.GetValueOrDefault();
        set => __pbn__Ecdm = value;
    }
    public bool ShouldSerializeEcdm() => __pbn__Ecdm != null;
    public void ResetEcdm() => __pbn__Ecdm = null;
    private int? __pbn__Ecdm;

    [global::ProtoBuf.ProtoMember(2, Name = @"reply_id")]
    public required int ReplyId { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"reply_id2")]
    public required int ReplyId2 { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
