// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hua.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class NotificationResetRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hua";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ecfd")]
    public int Ecfd
    {
        get => __pbn__Ecfd.GetValueOrDefault();
        set => __pbn__Ecfd = value;
    }
    public bool ShouldSerializeEcfd() => __pbn__Ecfd != null;
    public void ResetEcfd() => __pbn__Ecfd = null;
    private int? __pbn__Ecfd;

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
