// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hvj.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class MountDataErrorEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hvj";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ecjx")]
    public required Hvh Ecjx { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"hvh")]
    public enum Hvh
    {
        [global::ProtoBuf.ProtoEnum(Name = @"HVH_DHNJ")]
        HvhDhnj = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"HVH_DHNK")]
        HvhDhnk = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"HVH_DHNL")]
        HvhDhnl = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"HVH_DHNM")]
        HvhDhnm = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
