// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hwd.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class JobCrafterDirectoryPlayerInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hwd";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ecng")]
    public required long Ecng { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ecnh")]
    public required Gender Ecnh { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ecni")]
    public required Jcr Ecni { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ecnj")]
    public required CharacterStatus Ecnj { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ecnk")]
    public required MapExtendedCoordinates Ecnk { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"ecnl")]
    public required bool Ecnl { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"ecnm")]
    public required bool Ecnm { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"ecnn")]
    public required int Ecnn { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"ecno")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ecno { get; set; } = "";

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
