// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hwe.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class JobLevelUpEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hwe";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ecns")]
    public required JobDescription Ecns { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ecnt")]
    public required int Ecnt { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ecnu", IsPacked = true)]
    public required global::System.Collections.Generic.List<long> Ecnus { get; set; } = new global::System.Collections.Generic.List<long>();

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
