// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hwo.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class JobDescription : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hwo";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ecox")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ecox { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"ecoy")]
    public required int Ecoy { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ecoz")]
    public required global::System.Collections.Generic.List<Hwm> Ecozs { get; set; } = new global::System.Collections.Generic.List<Hwm>();

    [global::ProtoBuf.ProtoContract(Name = @"hwm")]
    public partial class Hwm : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".hwm";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"ecoq")]
        public required int Ecoq { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"ecor")]
        public Hwk Ecor
        {
            get => __pbn__ecot.Is(1) ? ((Hwk)__pbn__ecot.Object) : default;
            set => __pbn__ecot = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeEcor() => __pbn__ecot.Is(1);
        public void ResetEcor() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ecot, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__ecot;

        [global::ProtoBuf.ProtoMember(2, Name = @"ecos")]
        public Hwj Ecos
        {
            get => __pbn__ecot.Is(2) ? ((Hwj)__pbn__ecot.Object) : default;
            set => __pbn__ecot = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeEcos() => __pbn__ecot.Is(2);
        public void ResetEcos() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ecot, 2);

        public EcotOneofCase EcotCase => (EcotOneofCase)__pbn__ecot.Discriminator;

        public enum EcotOneofCase
        {
            None = 0,
            Ecor = 1,
            Ecos = 2,
        }

        [global::ProtoBuf.ProtoContract(Name = @"hwk")]
        public partial class Hwk : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".hwk";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"ecom")]
            public required int Ecom { get; set; }

        }

        [global::ProtoBuf.ProtoContract(Name = @"hwj")]
        public partial class Hwj : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".hwj";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"ecoh")]
            public required Hwh Ecoh { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"ecoi")]
            public required int Ecoi { get; set; }

            [global::ProtoBuf.ProtoContract(Name = @"hwh")]
            public partial class Hwh : global::ProtoBuf.IExtensible, IProtoMessage
            {
                public static string TypeUrl => ".hwh";
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"ecoc")]
                public required int Ecoc { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"ecod")]
                public required int Ecod { get; set; }

            }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
