// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hwr.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class JobMultiCraftStateEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hwr";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ecpi")]
    public required bool Ecpi { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ecpj")]
    public required Hwp Ecpj { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"hwp")]
    public partial class Hwp : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".hwp";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ecpd", IsPacked = true)]
        public required global::System.Collections.Generic.List<int> Ecpds { get; set; } = new global::System.Collections.Generic.List<int>();

        [global::ProtoBuf.ProtoMember(2, Name = @"ecpe")]
        public required long Ecpe { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
