// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hxs.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ObjectSetPositionRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hxs";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"object_uid")]
    public required int ObjectUid { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"position")]
    public required int Position { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"quantity")]
    public required int Quantity { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"quantity2")]
    public required int Quantity2 { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
