// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hxt.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ObjectFeedRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hxt";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ecuj")]
    public required global::System.Collections.Generic.List<ObjectUidWithQuantity> Ecujs { get; set; } = new global::System.Collections.Generic.List<ObjectUidWithQuantity>();

    [global::ProtoBuf.ProtoMember(2, Name = @"ecuk")]
    public long Ecuk
    {
        get => __pbn__Ecuk.GetValueOrDefault();
        set => __pbn__Ecuk = value;
    }
    public bool ShouldSerializeEcuk() => __pbn__Ecuk != null;
    public void ResetEcuk() => __pbn__Ecuk = null;
    private long? __pbn__Ecuk;

    [global::ProtoBuf.ProtoMember(3, Name = @"ecum")]
    public required int Ecum { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
