// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hyn.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class SetUpdateEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hyn";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ecyi", IsPacked = true)]
    public required global::System.Collections.Generic.List<int> Ecyis { get; set; } = new global::System.Collections.Generic.List<int>();

    [global::ProtoBuf.ProtoMember(2, Name = @"ecyj")]
    public required global::System.Collections.Generic.List<ObjectEffect> Ecyjs { get; set; } = new global::System.Collections.Generic.List<ObjectEffect>();

    [global::ProtoBuf.ProtoMember(3, Name = @"ecyk")]
    public required int Ecyk { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
