// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hyw.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ObjectFavoriteRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hyw";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eczw")]
    public required global::System.Collections.Generic.List<Hyu> Eczws { get; set; } = new global::System.Collections.Generic.List<Hyu>();

    [global::ProtoBuf.ProtoMember(2, Name = @"eczx")]
    public required bool Eczx { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"hyu")]
    public partial class Hyu : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".hyu";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eczr")]
        public required int Eczr { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"eczs")]
        public required int Eczs { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
