// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: hzq.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class HouseSellingUpdateEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hzq";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eddt")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Eddt { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"eddu")]
    public required long Eddu { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"eddv")]
    public required bool Eddv { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"eddw")]
    public required int Eddw { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"eddx")]
    public required int Eddx { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"eddy")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Eddy { get; set; } = "";

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
