// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: iar.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class HavenBagInvitationClosedEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "iar";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"edjb")]
    public int Edjb
    {
        get => __pbn__Edjb.GetValueOrDefault();
        set => __pbn__Edjb = value;
    }
    public bool ShouldSerializeEdjb() => __pbn__Edjb != null;
    public void ResetEdjb() => __pbn__Edjb = null;
    private int? __pbn__Edjb;

    [global::ProtoBuf.ProtoMember(2, Name = @"edjd")]
    public required Character Edjd { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
