// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: iav.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class HavenBagRoomUpdateEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "iav";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"edjo")]
    public required Ias Edjo { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"edjp")]
    public required global::System.Collections.Generic.List<Iat> Edjps { get; set; } = new global::System.Collections.Generic.List<Iat>();

    [global::ProtoBuf.ProtoContract(Name = @"iat")]
    public partial class Iat : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".iat";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"edjh")]
        public required int Edjh { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"edji")]
        public bool Edji
        {
            get => __pbn__Edji.GetValueOrDefault();
            set => __pbn__Edji = value;
        }
        public bool ShouldSerializeEdji() => __pbn__Edji != null;
        public void ResetEdji() => __pbn__Edji = null;
        private bool? __pbn__Edji;

        [global::ProtoBuf.ProtoMember(3, Name = @"edjk")]
        public required int Edjk { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"ias")]
    public enum Ias
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IAS_DIUX")]
        IasDiux = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IAS_DIUY")]
        IasDiuy = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
