// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: icw.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class GuildGeneralInformationEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "icw";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"edrl")]
    public required long Edrl { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"edrm")]
    public required int Edrm { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"edrn")]
    public required int Edrn { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"edro")]
    public required long Edro { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"edrp")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Edrp { get; set; } = "";

    [global::ProtoBuf.ProtoMember(6, Name = @"edrq")]
    public required bool Edrq { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"edrr")]
    public required int Edrr { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"edrs")]
    public required long Edrs { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
