// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: idu.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class GuildInvitationStateRecruiterEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "idu";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"edvo")]
    public required int Edvo { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"edvp")]
    public required Jdo Edvp { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"edvq")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Edvq { get; set; } = "";

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
