// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ieh.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class GuildChestTabContributionsEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ieh";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"edxk")]
    public required global::System.Collections.Generic.List<Ief> Edxks { get; set; } = new global::System.Collections.Generic.List<Ief>();

    [global::ProtoBuf.ProtoContract(Name = @"ief")]
    public partial class Ief : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".ief";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"edxe")]
        public required long Edxe { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"edxf")]
        public required long Edxf { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"edxg")]
        [global::System.ComponentModel.DefaultValue("")]
        public required string Edxg { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
