// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: iep.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class GuildChestTabContributionEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "iep";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"edyt")]
    public required int Edyt { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"edyu")]
    public required long Edyu { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"edyv")]
    public required long Edyv { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"edyw")]
    public required long Edyw { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"edyx")]
    public required long Edyx { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
