// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ifc.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class GuildApplicationPlayerEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ifc";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eeba")]
    public required Ifa Eeba { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"eebb")]
    public required Ifa Eebb { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"ifa")]
    public partial class Ifa : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".ifa";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eeav")]
        public required SocialApplicationInformation Eeav { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"eeaw")]
        public required GuildInformation Eeaw { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
