// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ifo.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class MapComplementaryInformationEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ifo";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"subarea_id")]
    public required int SubareaId { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"interactive_elements")]
    public required global::System.Collections.Generic.List<InteractiveElement> InteractiveElements { get; set; } = new global::System.Collections.Generic.List<InteractiveElement>();

    [global::ProtoBuf.ProtoMember(5, Name = @"map_id")]
    public required long MapId { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"stated_elements")]
    public required global::System.Collections.Generic.List<StatedElement> StatedElements { get; set; } = new global::System.Collections.Generic.List<StatedElement>();

    [global::ProtoBuf.ProtoMember(9, Name = @"obstacles")]
    public required global::System.Collections.Generic.List<MapObstacle> Obstacles { get; set; } = new global::System.Collections.Generic.List<MapObstacle>();

    [global::ProtoBuf.ProtoMember(10, Name = @"fights")]
    public required global::System.Collections.Generic.List<FightCommonInformation> Fights { get; set; } = new global::System.Collections.Generic.List<FightCommonInformation>();

    [global::ProtoBuf.ProtoMember(12, Name = @"has_aggressive_monsters")]
    public required bool HasAggressiveMonsters { get; set; }

    [global::ProtoBuf.ProtoMember(13, Name = @"actors")]
    public required global::System.Collections.Generic.List<ActorPositionInformation> Actors { get; set; } = new global::System.Collections.Generic.List<ActorPositionInformation>();

    [global::ProtoBuf.ProtoMember(14, Name = @"houses")]
    public required global::System.Collections.Generic.List<House> Houses { get; set; } = new global::System.Collections.Generic.List<House>();

    [global::ProtoBuf.ProtoMember(2, Name = @"in_house_information")]
    public MapComplementaryInHouseInformation InHouseInformation
    {
        get => __pbn__specific_complementary_information.Is(2) ? ((MapComplementaryInHouseInformation)__pbn__specific_complementary_information.Object) : default;
        set => __pbn__specific_complementary_information = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeInHouseInformation() => __pbn__specific_complementary_information.Is(2);
    public void ResetInHouseInformation() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__specific_complementary_information, 2);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__specific_complementary_information;

    [global::ProtoBuf.ProtoMember(4, Name = @"breach_information")]
    public MapComplementaryBreachInformation BreachInformation
    {
        get => __pbn__specific_complementary_information.Is(4) ? ((MapComplementaryBreachInformation)__pbn__specific_complementary_information.Object) : default;
        set => __pbn__specific_complementary_information = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
    }
    public bool ShouldSerializeBreachInformation() => __pbn__specific_complementary_information.Is(4);
    public void ResetBreachInformation() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__specific_complementary_information, 4);

    [global::ProtoBuf.ProtoMember(6, Name = @"haven_bag_information")]
    public MapComplementaryHavenBagInformation HavenBagInformation
    {
        get => __pbn__specific_complementary_information.Is(6) ? ((MapComplementaryHavenBagInformation)__pbn__specific_complementary_information.Object) : default;
        set => __pbn__specific_complementary_information = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
    }
    public bool ShouldSerializeHavenBagInformation() => __pbn__specific_complementary_information.Is(6);
    public void ResetHavenBagInformation() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__specific_complementary_information, 6);

    [global::ProtoBuf.ProtoMember(7, Name = @"anomaly_information")]
    public MapComplementaryAnomalyInformation AnomalyInformation
    {
        get => __pbn__specific_complementary_information.Is(7) ? ((MapComplementaryAnomalyInformation)__pbn__specific_complementary_information.Object) : default;
        set => __pbn__specific_complementary_information = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
    }
    public bool ShouldSerializeAnomalyInformation() => __pbn__specific_complementary_information.Is(7);
    public void ResetAnomalyInformation() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__specific_complementary_information, 7);

    [global::ProtoBuf.ProtoMember(11, Name = @"coordinates")]
    public MapCoordinates Coordinates
    {
        get => __pbn__specific_complementary_information.Is(11) ? ((MapCoordinates)__pbn__specific_complementary_information.Object) : default;
        set => __pbn__specific_complementary_information = new global::ProtoBuf.DiscriminatedUnionObject(11, value);
    }
    public bool ShouldSerializeCoordinates() => __pbn__specific_complementary_information.Is(11);
    public void ResetCoordinates() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__specific_complementary_information, 11);

    public SpecificComplementaryInformationOneofCase SpecificComplementaryInformationCase => (SpecificComplementaryInformationOneofCase)__pbn__specific_complementary_information.Discriminator;

    public enum SpecificComplementaryInformationOneofCase
    {
        None = 0,
        InHouseInformation = 2,
        BreachInformation = 4,
        HavenBagInformation = 6,
        AnomalyInformation = 7,
        Coordinates = 11,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
