// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: igp.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class MapMovementEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "igp";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"direction")]
    public int Direction
    {
        get => __pbn__Direction.GetValueOrDefault();
        set => __pbn__Direction = value;
    }
    public bool ShouldSerializeDirection() => __pbn__Direction != null;
    public void ResetDirection() => __pbn__Direction = null;
    private int? __pbn__Direction;

    [global::ProtoBuf.ProtoMember(2, Name = @"cells", IsPacked = true)]
    public required global::System.Collections.Generic.List<int> Cells { get; set; } = new global::System.Collections.Generic.List<int>();

    [global::ProtoBuf.ProtoMember(3, Name = @"character_id")]
    public required long CharacterId { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"cautious")]
    public required bool Cautious { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
