// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ihn.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class GameActionUpdateEffectTriggerCountEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ihn";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eemb")]
    [global::ProtoBuf.ProtoMap]
    public required global::System.Collections.Generic.Dictionary<long, long> Eembs { get; set; } = new global::System.Collections.Generic.Dictionary<long, long>();

    [global::ProtoBuf.ProtoMember(2, Name = @"eemc")]
    public required global::System.Collections.Generic.List<Ihl> Eemcs { get; set; } = new global::System.Collections.Generic.List<Ihl>();

    [global::ProtoBuf.ProtoContract(Name = @"ihl")]
    public partial class Ihl : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".ihl";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eelu")]
        public required int Eelu { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"eelv")]
        public required int Eelv { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"eelw")]
        public required int Eelw { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"eelx")]
        public required long Eelx { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
