// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ikc.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightChallengeJoinRefuseEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ikc";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eeyk")]
    public required Ika Eeyk { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"eeyl")]
    public required long Eeyl { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"ika")]
    public enum Ika
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXB")]
        IkaDkxb = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXC")]
        IkaDkxc = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXD")]
        IkaDkxd = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXE")]
        IkaDkxe = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXF")]
        IkaDkxf = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXG")]
        IkaDkxg = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXH")]
        IkaDkxh = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXI")]
        IkaDkxi = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXJ")]
        IkaDkxj = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXK")]
        IkaDkxk = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXL")]
        IkaDkxl = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXM")]
        IkaDkxm = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXN")]
        IkaDkxn = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXO")]
        IkaDkxo = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXP")]
        IkaDkxp = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXQ")]
        IkaDkxq = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXR")]
        IkaDkxr = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXS")]
        IkaDkxs = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXT")]
        IkaDkxt = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXU")]
        IkaDkxu = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXV")]
        IkaDkxv = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXW")]
        IkaDkxw = 21,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXX")]
        IkaDkxx = 22,
        [global::ProtoBuf.ProtoEnum(Name = @"IKA_DKXY")]
        IkaDkxy = 23,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
