// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ikr.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightMapInformationResponse : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ikr";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"efcp")]
    public required FightStartingPositions Efcp { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"efcq")]
    public required long Efcq { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"efcr")]
    public int Efcr
    {
        get => __pbn__Efcr.GetValueOrDefault();
        set => __pbn__Efcr = value;
    }
    public bool ShouldSerializeEfcr() => __pbn__Efcr != null;
    public void ResetEfcr() => __pbn__Efcr = null;
    private int? __pbn__Efcr;

    [global::ProtoBuf.ProtoMember(4, Name = @"efct")]
    public required long Efct { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
