// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ikv.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightScenarioEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ikv";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"efdl")]
    public required global::System.Collections.Generic.List<Ikt> Efdls { get; set; } = new global::System.Collections.Generic.List<Ikt>();

    [global::ProtoBuf.ProtoContract(Name = @"ikt")]
    public partial class Ikt : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".ikt";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"efdg")]
        public required int Efdg { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"efdh")]
        public required long Efdh { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
