// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: iky.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightSlaveSwitchContextEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "iky";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"efea")]
    public required CharacterCharacteristics Efea { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"efeb")]
    public required global::System.Collections.Generic.List<Shortcut> Efebs { get; set; } = new global::System.Collections.Generic.List<Shortcut>();

    [global::ProtoBuf.ProtoMember(3, Name = @"efec")]
    public required int Efec { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"efed")]
    public required long Efed { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"efee")]
    public required global::System.Collections.Generic.List<SpellItem> Efees { get; set; } = new global::System.Collections.Generic.List<SpellItem>();

    [global::ProtoBuf.ProtoMember(6, Name = @"efef")]
    public required long Efef { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
