// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ilf.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FighterIdentity : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ilf";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(2, Name = @"effa")]
    public required long Effa { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"effb")]
    public required Jdd Effb { get; set; }

    [global::ProtoBuf.ProtoMember(1, Name = @"effc")]
    public Ilb Effc
    {
        get => __pbn__effg.Is(1) ? ((Ilb)__pbn__effg.Object) : default;
        set => __pbn__effg = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializeEffc() => __pbn__effg.Is(1);
    public void ResetEffc() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__effg, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__effg;

    [global::ProtoBuf.ProtoMember(3, Name = @"effd")]
    public Ild Effd
    {
        get => __pbn__effg.Is(3) ? ((Ild)__pbn__effg.Object) : default;
        set => __pbn__effg = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
    }
    public bool ShouldSerializeEffd() => __pbn__effg.Is(3);
    public void ResetEffd() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__effg, 3);

    [global::ProtoBuf.ProtoMember(4, Name = @"effe")]
    public Ilc Effe
    {
        get => __pbn__effg.Is(4) ? ((Ilc)__pbn__effg.Object) : default;
        set => __pbn__effg = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
    }
    public bool ShouldSerializeEffe() => __pbn__effg.Is(4);
    public void ResetEffe() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__effg, 4);

    [global::ProtoBuf.ProtoMember(6, Name = @"efff")]
    public Ila Efff
    {
        get => __pbn__effg.Is(6) ? ((Ila)__pbn__effg.Object) : default;
        set => __pbn__effg = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
    }
    public bool ShouldSerializeEfff() => __pbn__effg.Is(6);
    public void ResetEfff() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__effg, 6);

    public EffgOneofCase EffgCase => (EffgOneofCase)__pbn__effg.Discriminator;

    public enum EffgOneofCase
    {
        None = 0,
        Effc = 1,
        Effd = 3,
        Effe = 4,
        Efff = 6,
    }

    [global::ProtoBuf.ProtoContract(Name = @"ilb")]
    public partial class Ilb : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".ilb";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"efem")]
        public required int Efem { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"ild")]
    public partial class Ild : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".ild";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"efev")]
        public required int Efev { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"efew")]
        public required FighterIdentity Efew { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"ilc")]
    public partial class Ilc : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".ilc";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"efeq")]
        public required int Efeq { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"efer")]
        public required FighterIdentity Efer { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"ila")]
    public partial class Ila : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".ila";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
