// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: imb.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightPlacementSwapPositionsOfferEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "imb";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"efjl")]
    public required int Efjl { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"efjm")]
    public required int Efjm { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"efjn")]
    public required int Efjn { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"efjo")]
    public required long Efjo { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"efjp")]
    public required long Efjp { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
