// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: imv.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ExchangeBidSellerStartedEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "imv";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"efmp")]
    public required SellingConditions Efmp { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"efmq")]
    public required global::System.Collections.Generic.List<Imt> Efmqs { get; set; } = new global::System.Collections.Generic.List<Imt>();

    [global::ProtoBuf.ProtoContract(Name = @"imt")]
    public partial class Imt : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".imt";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"efmj")]
        public required int Efmj { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"efmk")]
        public required BidItem Efmk { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"efml")]
        public required long Efml { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
