// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: inq.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ExchangeItemAutoCraftStoppedEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "inq";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"efqq")]
    public required Ino Efqq { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"ino")]
    public enum Ino
    {
        [global::ProtoBuf.ProtoEnum(Name = @"INO_DLYF")]
        InoDlyf = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"INO_DLYG")]
        InoDlyg = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"INO_DLYH")]
        InoDlyh = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"INO_DLYI")]
        InoDlyi = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
