// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ioo.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ExchangeObjectsSellRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ioo";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"efuc")]
    public required global::System.Collections.Generic.List<Iom> Efucs { get; set; } = new global::System.Collections.Generic.List<Iom>();

    [global::ProtoBuf.ProtoContract(Name = @"iom")]
    public partial class Iom : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".iom";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eftx")]
        public required int Eftx { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"efty")]
        public required int Efty { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
