// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ios.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ExchangeBidPriceEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ios";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"efur")]
    public required Ioq Efur { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"efus")]
    public required long Efus { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"efut")]
    public required int Efut { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"ioq")]
    public partial class Ioq : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".ioq";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"efum")]
        public required bool Efum { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"efun", IsPacked = true)]
        public required global::System.Collections.Generic.List<long> Efuns { get; set; } = new global::System.Collections.Generic.List<long>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
