// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ipi.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ExchangeStartedWithPodsEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ipi";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"efxq")]
    public required long Efxq { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"efxr")]
    public required int Efxr { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"efxs")]
    public required int Efxs { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"efxt")]
    public required int Efxt { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"efxu")]
    public required int Efxu { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"efxv")]
    public required Jcx Efxv { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"efxw")]
    public required long Efxw { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
