// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: iqj.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class DecraftResultEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "iqj";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"egcc")]
    public required global::System.Collections.Generic.List<Iqh> Egccs { get; set; } = new global::System.Collections.Generic.List<Iqh>();

    [global::ProtoBuf.ProtoContract(Name = @"iqh")]
    public partial class Iqh : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".iqh";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"egbv")]
        public required global::System.Collections.Generic.List<Iqf> Egbvs { get; set; } = new global::System.Collections.Generic.List<Iqf>();

        [global::ProtoBuf.ProtoMember(2, Name = @"egbw")]
        public required float Egbw { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"egbx")]
        public required int Egbx { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"egby")]
        public required float Egby { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"iqf")]
        public partial class Iqf : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".iqf";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"egbq")]
            public required int Egbq { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"egbr")]
            public required int Egbr { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
