// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: iqp.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ExchangeObjectsAddedEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "iqp";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"egdb")]
    public required bool Egdb { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"egdc")]
    public required global::System.Collections.Generic.List<ObjectItemInventory> Egdcs { get; set; } = new global::System.Collections.Generic.List<ObjectItemInventory>();

    [global::ProtoBuf.ProtoMember(3, Name = @"egdd")]
    public float Egdd
    {
        get => __pbn__Egdd.GetValueOrDefault();
        set => __pbn__Egdd = value;
    }
    public bool ShouldSerializeEgdd() => __pbn__Egdd != null;
    public void ResetEgdd() => __pbn__Egdd = null;
    private float? __pbn__Egdd;

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
