// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: iri.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ObjectAveragePricesRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "iri";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eggy")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Eggy
    {
        get => __pbn__Eggy ?? "";
        set => __pbn__Eggy = value;
    }
    public bool ShouldSerializeEggy() => __pbn__Eggy != null;
    public void ResetEggy() => __pbn__Eggy = null;
    private string __pbn__Eggy;

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
