// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: isd.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class LockableCodeResultEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "isd";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"egkh")]
    public required Isb Egkh { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"isb")]
    public enum Isb
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ISB_DMXX")]
        IsbDmxx = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ISB_DMXY")]
        IsbDmxy = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ISB_DMXZ")]
        IsbDmxz = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
