// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: isv.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ChangeAppearanceDialogStart : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "isv";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"egmd")]
    public required Ist Egmd { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"ist")]
    public enum Ist
    {
        [global::ProtoBuf.ProtoEnum(Name = @"IST_DNAG")]
        IstDnag = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"IST_DNAH")]
        IstDnah = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"IST_DNAI")]
        IstDnai = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"IST_DNAJ")]
        IstDnaj = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"IST_DNAK")]
        IstDnak = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"IST_DNAL")]
        IstDnal = 5,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
