// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: itl.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class DebtsDeleteEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "itl";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"egnr")]
    public required Itj Egnr { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"egns", IsPacked = true)]
    public required global::System.Collections.Generic.List<long> Egns { get; set; } = new global::System.Collections.Generic.List<long>();

    [global::ProtoBuf.ProtoContract(Name = @"itj")]
    public enum Itj
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ITJ_DNCR")]
        ItjDncr = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ITJ_DNCS")]
        ItjDncs = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ITJ_DNCT")]
        ItjDnct = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"ITJ_DNCU")]
        ItjDncu = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
