// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: iud.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ContextCreationEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "iud";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"context")]
    public required GameContext Context { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"egqk")]
    [global::ProtoBuf.ProtoMap]
    public required global::System.Collections.Generic.Dictionary<int, string> Egqks { get; set; } = new global::System.Collections.Generic.Dictionary<int, string>();

    [global::ProtoBuf.ProtoContract()]
    public enum GameContext
    {
        [global::ProtoBuf.ProtoEnum(Name = @"ROLE_PLAY")]
        RolePlay = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"FIGHT")]
        Fight = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
