// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ivn.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class BlockEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ivn";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"egut")]
    public Ivl Egut
    {
        get => __pbn__eguv.Is(1) ? ((Ivl)__pbn__eguv.Object) : default;
        set => __pbn__eguv = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializeEgut() => __pbn__eguv.Is(1);
    public void ResetEgut() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eguv, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__eguv;

    [global::ProtoBuf.ProtoMember(2, Name = @"eguu")]
    public Ivk Eguu
    {
        get => __pbn__eguv.Is(2) ? ((Ivk)__pbn__eguv.Object) : default;
        set => __pbn__eguv = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeEguu() => __pbn__eguv.Is(2);
    public void ResetEguu() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eguv, 2);

    public EguvOneofCase EguvCase => (EguvOneofCase)__pbn__eguv.Discriminator;

    public enum EguvOneofCase
    {
        None = 0,
        Egut = 1,
        Eguu = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"ivl")]
    public partial class Ivl : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".ivl";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eguo")]
        public required bool Eguo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"egup")]
        public required ContactInformation Egup { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"ivk")]
    public partial class Ivk : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".ivk";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eguk")]
        public required Iuf Eguk { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
