// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: iwd.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FriendInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "iwd";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"egxx")]
    public required Iwb Egxx { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"egxy")]
    public required long Egxy { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"egxz")]
    public required long Egxz { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"egya")]
    public required AccountTag Egya { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"egyb")]
    public required int Egyb { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"egyc")]
    public required Jcq Egyc { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"iwb")]
    public partial class Iwb : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".iwb";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"egxh")]
        public required AllianceInformation Egxh { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"egxi")]
        public required Jcr Egxi { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"egxj")]
        public required CharacterStatus Egxj { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"egxk")]
        public required int Egxk { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"egxl")]
        public required int Egxl { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"egxm")]
        public required GuildInformation Egxm { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"egxn")]
        public required int Egxn { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"egxo")]
        [global::System.ComponentModel.DefaultValue("")]
        public required string Egxo { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"egxp")]
        public required long Egxp { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"egxq")]
        public required bool Egxq { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"egxr")]
        public required int Egxr { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"egxs")]
        public required int Egxs { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"egxt")]
        public required Gender Egxt { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
