// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ixw.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public enum Channel
{
    [global::ProtoBuf.ProtoEnum(Name = @"GLOBAL")]
    Global = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"TEAM")]
    Team = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"GUILD")]
    Guild = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"ALLIANCE")]
    Alliance = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"PARTY")]
    Party = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"SALES")]
    Sales = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"SEEK")]
    Seek = 6,
    [global::ProtoBuf.ProtoEnum(Name = @"NOOB")]
    Noob = 7,
    [global::ProtoBuf.ProtoEnum(Name = @"ADMIN")]
    Admin = 8,
    [global::ProtoBuf.ProtoEnum(Name = @"ARENA")]
    Arena = 9,
    [global::ProtoBuf.ProtoEnum(Name = @"PRIVATE")]
    Private = 10,
    [global::ProtoBuf.ProtoEnum(Name = @"INFO")]
    Info = 12,
    [global::ProtoBuf.ProtoEnum(Name = @"FIGHT_LOG")]
    FightLog = 13,
    [global::ProtoBuf.ProtoEnum(Name = @"ADS")]
    Ads = 14,
    [global::ProtoBuf.ProtoEnum(Name = @"EVENT")]
    Event = 15,
    [global::ProtoBuf.ProtoEnum(Name = @"EXCHANGE")]
    Exchange = 16,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
