// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: ixy.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ChatChannelMessageEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "ixy";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"content")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Content { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"origin_server_id")]
    public int OriginServerId
    {
        get => __pbn__OriginServerId.GetValueOrDefault();
        set => __pbn__OriginServerId = value;
    }
    public bool ShouldSerializeOriginServerId() => __pbn__OriginServerId != null;
    public void ResetOriginServerId() => __pbn__OriginServerId = null;
    private int? __pbn__OriginServerId;

    [global::ProtoBuf.ProtoMember(3, Name = @"from_admin")]
    public required bool FromAdmin { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"sender_character_id")]
    public required long SenderCharacterId { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"date")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Date { get; set; } = "";

    [global::ProtoBuf.ProtoMember(6, Name = @"channel")]
    public required Channel Channel { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"sender_prefix")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string SenderPrefix { get; set; } = "";

    [global::ProtoBuf.ProtoMember(8, Name = @"sender_name")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string SenderName { get; set; } = "";

    [global::ProtoBuf.ProtoMember(9, Name = @"sender_account_id")]
    public required long SenderAccountId { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"object")]
    public required global::System.Collections.Generic.List<ObjectItemInventory> Objects { get; set; } = new global::System.Collections.Generic.List<ObjectItemInventory>();

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
