// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: iyh.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ChatPrivateCopyMessageEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "iyh";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ehgy")]
    public required global::System.Collections.Generic.List<ObjectItemInventory> Ehgies { get; set; } = new global::System.Collections.Generic.List<ObjectItemInventory>();

    [global::ProtoBuf.ProtoMember(2, Name = @"ehgz")]
    public required int Ehgz { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ehha")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ehha { get; set; } = "";

    [global::ProtoBuf.ProtoMember(4, Name = @"ehhb")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ehhb { get; set; } = "";

    [global::ProtoBuf.ProtoMember(5, Name = @"ehhc")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ehhc { get; set; } = "";

    [global::ProtoBuf.ProtoMember(6, Name = @"ehhd")]
    public required long Ehhd { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
