// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jae.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class CharacterSelectionEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jae";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"success")]
    public Success SuccessValue
    {
        get => __pbn__result.Is(1) ? ((Success)__pbn__result.Object) : default;
        set => __pbn__result = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializeSuccessValue() => __pbn__result.Is(1);
    public void ResetSuccessValue() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__result, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__result;

    [global::ProtoBuf.ProtoMember(2, Name = @"error")]
    public Error ErrorValue
    {
        get => __pbn__result.Is(2) ? ((Error)__pbn__result.Object) : default;
        set => __pbn__result = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeErrorValue() => __pbn__result.Is(2);
    public void ResetErrorValue() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__result, 2);

    public ResultOneofCase ResultCase => (ResultOneofCase)__pbn__result.Discriminator;

    public enum ResultOneofCase
    {
        None = 0,
        SuccessValue = 1,
        ErrorValue = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Success : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".Success";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ehmy")]
        [global::ProtoBuf.ProtoMap]
        public required global::System.Collections.Generic.Dictionary<bool, bool> Ehmies { get; set; } = new global::System.Collections.Generic.Dictionary<bool, bool>();

        [global::ProtoBuf.ProtoMember(2, Name = @"character")]
        public required Character Character { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Error : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".Error";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
