// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jcm.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract(Name = @"jcm")]
public enum Jcm
{
    [global::ProtoBuf.ProtoEnum(Name = @"JCM_DOWD")]
    JcmDowd = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"JCM_DOWE")]
    JcmDowe = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"JCM_DOWF")]
    JcmDowf = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"JCM_DOWG")]
    JcmDowg = 3,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
