// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jct.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract(Name = @"jct")]
public enum Jct
{
    [global::ProtoBuf.ProtoEnum(Name = @"JCT_DOXD")]
    JctDoxd = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"JCT_DOXE")]
    JctDoxe = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"JCT_DOXF")]
    JctDoxf = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"JCT_DOXG")]
    JctDoxg = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"JCT_DOXH")]
    JctDoxh = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"JCT_DOXI")]
    JctDoxi = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"JCT_DOXJ")]
    JctDoxj = 6,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
