// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jcu.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract(Name = @"jcu")]
public enum Jcu
{
    [global::ProtoBuf.ProtoEnum(Name = @"JCU_DOXK")]
    JcuDoxk = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"JCU_DOXL")]
    JcuDoxl = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"JCU_DOXM")]
    JcuDoxm = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"JCU_DOXN")]
    JcuDoxn = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"JCU_DOXO")]
    JcuDoxo = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"JCU_DOXP")]
    JcuDoxp = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"JCU_DOXQ")]
    JcuDoxq = 6,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
