// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jcw.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public enum DialogType
{
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_BOOK")]
    DialogBook = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_DIALOG")]
    DialogDialog = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_LOCKABLE")]
    DialogLockable = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_PURCHASABLE")]
    DialogPurchasable = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_GUILD_INVITATION")]
    DialogGuildInvitation = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_GUILD_CREATE")]
    DialogGuildCreate = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_GUILD_RENAME")]
    DialogGuildRename = 6,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_MARRIAGE")]
    DialogMarriage = 7,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_DUNGEON_MEETING")]
    DialogDungeonMeeting = 8,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_SPELL_FORGET")]
    DialogSpellForget = 9,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_TELEPORTER")]
    DialogTeleporter = 10,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_EXCHANGE")]
    DialogExchange = 11,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_ALLIANCE_INVITATION")]
    DialogAllianceInvitation = 12,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_ALLIANCE_CREATE")]
    DialogAllianceCreate = 13,
    [global::ProtoBuf.ProtoEnum(Name = @"DIALOG_ALLIANCE_RENAME")]
    DialogAllianceRename = 14,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
