// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jdg.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract(Name = @"jdg")]
public enum Jdg
{
    [global::ProtoBuf.ProtoEnum(Name = @"JDG_DPBO")]
    JdgDpbo = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"JDG_DPBP")]
    JdgDpbp = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"JDG_DPBQ")]
    JdgDpbq = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"JDG_DPBR")]
    JdgDpbr = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"JDG_DPBS")]
    JdgDpbs = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"JDG_DPBT")]
    JdgDpbt = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"JDG_DPBU")]
    JdgDpbu = 6,
    [global::ProtoBuf.ProtoEnum(Name = @"JDG_DPBV")]
    JdgDpbv = 7,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
