// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jel.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class AllianceRecruitmentInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jel";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eiap")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Eiap { get; set; } = "";

    [global::ProtoBuf.ProtoMember(2, Name = @"eiaq")]
    public required Jdj Eiaq { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"eiar")]
    public required bool Eiar { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"eias")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Eias { get; set; } = "";

    [global::ProtoBuf.ProtoMember(5, Name = @"eiat", IsPacked = true)]
    public required global::System.Collections.Generic.List<int> Eiats { get; set; } = new global::System.Collections.Generic.List<int>();

    [global::ProtoBuf.ProtoMember(6, Name = @"eiau")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Eiau { get; set; } = "";

    [global::ProtoBuf.ProtoMember(7, Name = @"eiav")]
    public required int Eiav { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"eiaw", IsPacked = true)]
    public required global::System.Collections.Generic.List<int> Eiaws { get; set; } = new global::System.Collections.Generic.List<int>();

    [global::ProtoBuf.ProtoMember(9, Name = @"eiax")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Eiax { get; set; } = "";

    [global::ProtoBuf.ProtoMember(10, Name = @"eiay")]
    public required long Eiay { get; set; }

    [global::ProtoBuf.ProtoMember(11, Name = @"eiaz")]
    public required bool Eiaz { get; set; }

    [global::ProtoBuf.ProtoMember(12, Name = @"eiba")]
    public required bool Eiba { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
