// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jer.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class CharacterCharacteristic : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jer";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(3, Name = @"characteristic_id")]
    public required int CharacteristicId { get; set; }

    [global::ProtoBuf.ProtoMember(1, Name = @"value")]
    public CharacterCharacteristicValue Value
    {
        get => __pbn__eich.Is(1) ? ((CharacterCharacteristicValue)__pbn__eich.Object) : default;
        set => __pbn__eich = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializeValue() => __pbn__eich.Is(1);
    public void ResetValue() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eich, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__eich;

    [global::ProtoBuf.ProtoMember(2, Name = @"detailed")]
    public CharacterCharacteristicDetailed Detailed
    {
        get => __pbn__eich.Is(2) ? ((CharacterCharacteristicDetailed)__pbn__eich.Object) : default;
        set => __pbn__eich = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeDetailed() => __pbn__eich.Is(2);
    public void ResetDetailed() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eich, 2);

    [global::ProtoBuf.ProtoMember(4, Name = @"usable")]
    public CharacterCharacteristicDetailedUsable Usable
    {
        get => __pbn__eich.Is(4) ? ((CharacterCharacteristicDetailedUsable)__pbn__eich.Object) : default;
        set => __pbn__eich = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
    }
    public bool ShouldSerializeUsable() => __pbn__eich.Is(4);
    public void ResetUsable() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eich, 4);

    public EichOneofCase EichCase => (EichOneofCase)__pbn__eich.Discriminator;

    public enum EichOneofCase
    {
        None = 0,
        Value = 1,
        Detailed = 2,
        Usable = 4,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
