// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jhq.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class EntityLook : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jhq";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"sub_entities")]
    public required global::System.Collections.Generic.List<SubEntityInformation> SubEntities { get; set; } = new global::System.Collections.Generic.List<SubEntityInformation>();

    [global::ProtoBuf.ProtoMember(2, Name = @"bones_id")]
    public required int BonesId { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"indexed_colors", IsPacked = true)]
    public required global::System.Collections.Generic.List<int> IndexedColors { get; set; } = new global::System.Collections.Generic.List<int>();

    [global::ProtoBuf.ProtoMember(4, Name = @"skins", IsPacked = true)]
    public required global::System.Collections.Generic.List<int> Skins { get; set; } = new global::System.Collections.Generic.List<int>();

    [global::ProtoBuf.ProtoMember(5, Name = @"scales", IsPacked = true)]
    public required global::System.Collections.Generic.List<int> Scales { get; set; } = new global::System.Collections.Generic.List<int>();

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
