// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jik.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class SpellItem2 : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "hht";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eisy")]
    public required int Eisy { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"eisz")]
    public bool Eisz
    {
        get => __pbn__Eisz.GetValueOrDefault();
        set => __pbn__Eisz = value;
    }
    public bool ShouldSerializeEisz() => __pbn__Eisz != null;
    public void ResetEisz() => __pbn__Eisz = null;
    private bool? __pbn__Eisz;

    [global::ProtoBuf.ProtoMember(3, Name = @"eitb")]
    [global::ProtoBuf.ProtoMap]
    public required global::System.Collections.Generic.Dictionary<int, string> Eitbs { get; set; } = new global::System.Collections.Generic.Dictionary<int, string>();

    [global::ProtoBuf.ProtoMember(4, Name = @"eitc")]
    public required int Eitc { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
