// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jiv.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PaddockInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jiv";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eiuj")]
    public required int Eiuj { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"eiuk")]
    public required int Eiuk { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"eiul")]
    public Jit Eiul
    {
        get => __pbn__eiun.Is(2) ? ((Jit)__pbn__eiun.Object) : default;
        set => __pbn__eiun = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeEiul() => __pbn__eiun.Is(2);
    public void ResetEiul() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eiun, 2);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__eiun;

    [global::ProtoBuf.ProtoMember(3, Name = @"eium")]
    public Jio Eium
    {
        get => __pbn__eiun.Is(3) ? ((Jio)__pbn__eiun.Object) : default;
        set => __pbn__eiun = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
    }
    public bool ShouldSerializeEium() => __pbn__eiun.Is(3);
    public void ResetEium() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eiun, 3);

    public EiunOneofCase EiunCase => (EiunOneofCase)__pbn__eiun.Discriminator;

    public enum EiunOneofCase
    {
        None = 0,
        Eiul = 2,
        Eium = 3,
    }

    [global::ProtoBuf.ProtoContract(Name = @"jit")]
    public partial class Jit : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jit";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eiue")]
        public required global::System.Collections.Generic.List<Jir> Eiues { get; set; } = new global::System.Collections.Generic.List<Jir>();

        [global::ProtoBuf.ProtoMember(2, Name = @"eiuf")]
        public required global::System.Collections.Generic.List<Jir> Eiufs { get; set; } = new global::System.Collections.Generic.List<Jir>();

        [global::ProtoBuf.ProtoContract(Name = @"jir")]
        public partial class Jir : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jir";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"eity")]
            public required bool Eity { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"eitz")]
            public required long Eitz { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"eiua")]
            public required Jip Eiua { get; set; }

            [global::ProtoBuf.ProtoContract(Name = @"jip")]
            public partial class Jip : global::ProtoBuf.IExtensible, IProtoMessage
            {
                public static string TypeUrl => ".jip";
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"eitt")]
                public required GuildInformation Eitt { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"eitu")]
                public required bool Eitu { get; set; }

            }

        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"jio")]
    public partial class Jio : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jio";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eitm")]
        public required bool Eitm { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"eitn")]
        public required long Eitn { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"eito")]
        public required global::System.Collections.Generic.List<Jim> Eitoes { get; set; } = new global::System.Collections.Generic.List<Jim>();

        [global::ProtoBuf.ProtoMember(4, Name = @"eitp")]
        public required MapExtendedCoordinates Eitp { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"jim")]
        public partial class Jim : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jim";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"eitg")]
            [global::System.ComponentModel.DefaultValue("")]
            public required string Eitg { get; set; } = "";

            [global::ProtoBuf.ProtoMember(2, Name = @"eith")]
            [global::System.ComponentModel.DefaultValue("")]
            public required string Eith { get; set; } = "";

            [global::ProtoBuf.ProtoMember(3, Name = @"eiti")]
            public required int Eiti { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
