// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jjr.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightResultListEntry : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jjr";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eixx")]
    public required Jdb Eixx { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"eixy")]
    public required Jjd Eixy { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"eixz")]
    public required Jjp Eixz { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"eiya")]
    public required int Eiya { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"jjd")]
    public partial class Jjd : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jjd";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eivr")]
        public required long Eivr { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"eivs")]
        public required global::System.Collections.Generic.List<Jjb> Eivs { get; set; } = new global::System.Collections.Generic.List<Jjb>();

        [global::ProtoBuf.ProtoContract(Name = @"jjb")]
        public partial class Jjb : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jjb";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"eivl")]
            public required int Eivl { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"eivm")]
            public required int Eivm { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"eivn")]
            public required int Eivn { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"jjp")]
    public partial class Jjp : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jjp";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"eixn")]
        public required long Eixn { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"eixo")]
        public required bool Eixo { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"eixp")]
        public required Jjm Eixp { get; set; }

        [global::ProtoBuf.ProtoMember(1, Name = @"eixq")]
        public Jjm Eixq
        {
            get => __pbn__eixt.Is(1) ? ((Jjm)__pbn__eixt.Object) : default;
            set => __pbn__eixt = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeEixq() => __pbn__eixt.Is(1);
        public void ResetEixq() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eixt, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__eixt;

        [global::ProtoBuf.ProtoMember(5, Name = @"eixr")]
        public Jjn Eixr
        {
            get => __pbn__eixt.Is(5) ? ((Jjn)__pbn__eixt.Object) : default;
            set => __pbn__eixt = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeEixr() => __pbn__eixt.Is(5);
        public void ResetEixr() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eixt, 5);

        [global::ProtoBuf.ProtoMember(6, Name = @"eixs")]
        public Jjl Eixs
        {
            get => __pbn__eixt.Is(6) ? ((Jjl)__pbn__eixt.Object) : default;
            set => __pbn__eixt = new global::ProtoBuf.DiscriminatedUnionObject(6, value);
        }
        public bool ShouldSerializeEixs() => __pbn__eixt.Is(6);
        public void ResetEixs() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eixt, 6);

        public EixtOneofCase EixtCase => (EixtOneofCase)__pbn__eixt.Discriminator;

        public enum EixtOneofCase
        {
            None = 0,
            Eixq = 1,
            Eixr = 5,
            Eixs = 6,
        }

        [global::ProtoBuf.ProtoContract(Name = @"jjm")]
        public partial class Jjm : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jjm";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"eixf")]
            public required int Eixf { get; set; }

        }

        [global::ProtoBuf.ProtoContract(Name = @"jjn")]
        public partial class Jjn : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jjn";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"eixj")]
            public required AllianceInformation Eixj { get; set; }

        }

        [global::ProtoBuf.ProtoContract(Name = @"jjl")]
        public partial class Jjl : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jjl";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"eixa")]
            public required int Eixa { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"eixb")]
            public required global::System.Collections.Generic.List<Jjj> Eixbs { get; set; } = new global::System.Collections.Generic.List<Jjj>();

            [global::ProtoBuf.ProtoContract(Name = @"jjj")]
            public partial class Jjj : global::ProtoBuf.IExtensible, IProtoMessage
            {
                public static string TypeUrl => ".jjj";
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"eiwu")]
                public Jjg Eiwu
                {
                    get => __pbn__eiww.Is(1) ? ((Jjg)__pbn__eiww.Object) : default;
                    set => __pbn__eiww = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
                }
                public bool ShouldSerializeEiwu() => __pbn__eiww.Is(1);
                public void ResetEiwu() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eiww, 1);

                private global::ProtoBuf.DiscriminatedUnionObject __pbn__eiww;

                [global::ProtoBuf.ProtoMember(2, Name = @"eiwv")]
                public Jjh Eiwv
                {
                    get => __pbn__eiww.Is(2) ? ((Jjh)__pbn__eiww.Object) : default;
                    set => __pbn__eiww = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
                }
                public bool ShouldSerializeEiwv() => __pbn__eiww.Is(2);
                public void ResetEiwv() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eiww, 2);

                public EiwwOneofCase EiwwCase => (EiwwOneofCase)__pbn__eiww.Discriminator;

                public enum EiwwOneofCase
                {
                    None = 0,
                    Eiwu = 1,
                    Eiwv = 2,
                }

                [global::ProtoBuf.ProtoContract(Name = @"jjg")]
                public partial class Jjg : global::ProtoBuf.IExtensible, IProtoMessage
                {
                    public static string TypeUrl => ".jjg";
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"eivw")]
                    public required bool Eivw { get; set; }

                    [global::ProtoBuf.ProtoMember(2, Name = @"eivx")]
                    public required long Eivx { get; set; }

                    [global::ProtoBuf.ProtoMember(3, Name = @"eivy")]
                    public required int Eivy { get; set; }

                    [global::ProtoBuf.ProtoMember(4, Name = @"eivz")]
                    public required bool Eivz { get; set; }

                    [global::ProtoBuf.ProtoMember(5, Name = @"eiwa")]
                    public required long Eiwa { get; set; }

                    [global::ProtoBuf.ProtoMember(6, Name = @"eiwb")]
                    public required bool Eiwb { get; set; }

                    [global::ProtoBuf.ProtoMember(7, Name = @"eiwc")]
                    public required bool Eiwc { get; set; }

                    [global::ProtoBuf.ProtoMember(8, Name = @"eiwd")]
                    public required long Eiwd { get; set; }

                    [global::ProtoBuf.ProtoMember(9, Name = @"eiwe")]
                    public required bool Eiwe { get; set; }

                    [global::ProtoBuf.ProtoMember(10, Name = @"eiwf")]
                    public required long Eiwf { get; set; }

                    [global::ProtoBuf.ProtoMember(11, Name = @"eiwg")]
                    public required bool Eiwg { get; set; }

                    [global::ProtoBuf.ProtoMember(12, Name = @"eiwh")]
                    public required long Eiwh { get; set; }

                    [global::ProtoBuf.ProtoMember(13, Name = @"eiwi")]
                    public required long Eiwi { get; set; }

                }

                [global::ProtoBuf.ProtoContract(Name = @"jjh")]
                public partial class Jjh : global::ProtoBuf.IExtensible, IProtoMessage
                {
                    public static string TypeUrl => ".jjh";
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"eiwm")]
                    public required int Eiwm { get; set; }

                    [global::ProtoBuf.ProtoMember(2, Name = @"eiwn")]
                    public required int Eiwn { get; set; }

                    [global::ProtoBuf.ProtoMember(3, Name = @"eiwo")]
                    public required int Eiwo { get; set; }

                    [global::ProtoBuf.ProtoMember(4, Name = @"eiwp")]
                    public required int Eiwp { get; set; }

                    [global::ProtoBuf.ProtoMember(5, Name = @"eiwq")]
                    public required int Eiwq { get; set; }

                }

            }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
