// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jjt.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FighterLightInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jjt";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(2, Name = @"eiye")]
    public required bool Eiye { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"eiyf")]
    public required int Eiyf { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"eiyg")]
    public required long Eiyg { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"eiyh")]
    public required Gender Eiyh { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"eiyi")]
    public required int Eiyi { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"eiyj")]
    public required int Eiyj { get; set; }

    [global::ProtoBuf.ProtoMember(1, Name = @"eiyk")]
    public FighterTaxCollectorLightInformation Eiyk
    {
        get => __pbn__eiyo.Is(1) ? ((FighterTaxCollectorLightInformation)__pbn__eiyo.Object) : default;
        set => __pbn__eiyo = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializeEiyk() => __pbn__eiyo.Is(1);
    public void ResetEiyk() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eiyo, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__eiyo;

    [global::ProtoBuf.ProtoMember(5, Name = @"eiyl")]
    public FighterEntityLightInformation Eiyl
    {
        get => __pbn__eiyo.Is(5) ? ((FighterEntityLightInformation)__pbn__eiyo.Object) : default;
        set => __pbn__eiyo = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
    }
    public bool ShouldSerializeEiyl() => __pbn__eiyo.Is(5);
    public void ResetEiyl() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eiyo, 5);

    [global::ProtoBuf.ProtoMember(7, Name = @"eiym")]
    public FighterNamedLightInformation Eiym
    {
        get => __pbn__eiyo.Is(7) ? ((FighterNamedLightInformation)__pbn__eiyo.Object) : default;
        set => __pbn__eiyo = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
    }
    public bool ShouldSerializeEiym() => __pbn__eiyo.Is(7);
    public void ResetEiym() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eiyo, 7);

    [global::ProtoBuf.ProtoMember(9, Name = @"eiyn")]
    public FighterMonsterLightInformation Eiyn
    {
        get => __pbn__eiyo.Is(9) ? ((FighterMonsterLightInformation)__pbn__eiyo.Object) : default;
        set => __pbn__eiyo = new global::ProtoBuf.DiscriminatedUnionObject(9, value);
    }
    public bool ShouldSerializeEiyn() => __pbn__eiyo.Is(9);
    public void ResetEiyn() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__eiyo, 9);

    public EiyoOneofCase EiyoCase => (EiyoOneofCase)__pbn__eiyo.Discriminator;

    public enum EiyoOneofCase
    {
        None = 0,
        Eiyk = 1,
        Eiyl = 5,
        Eiym = 7,
        Eiyn = 9,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
