// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jjw.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class SocialFightInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jjw";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eiys")]
    public required bool Eiys { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"eiyt")]
    public required int Eiyt { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"eiyu")]
    public required long Eiyu { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"eiyv")]
    public required Jju Eiyv { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"jju")]
    public enum Jju
    {
        [global::ProtoBuf.ProtoEnum(Name = @"JJU_DQXD")]
        JjuDqxd = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"JJU_DQXE")]
        JjuDqxe = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
