// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jkb.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightTemporaryBoostEffect : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jkb";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(3, Name = @"eizm")]
    public required int Eizm { get; set; }

    [global::ProtoBuf.ProtoMember(1, Name = @"eizn")]
    public int Eizn
    {
        get => __pbn__eizu.Is(1) ? __pbn__eizu.Int32 : default;
        set => __pbn__eizu = new global::ProtoBuf.DiscriminatedUnion32Object(1, value);
    }
    public bool ShouldSerializeEizn() => __pbn__eizu.Is(1);
    public void ResetEizn() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__eizu, 1);

    private global::ProtoBuf.DiscriminatedUnion32Object __pbn__eizu;

    [global::ProtoBuf.ProtoMember(2, Name = @"eizp")]
    public int Eizp
    {
        get => __pbn__eizu.Is(2) ? __pbn__eizu.Int32 : default;
        set => __pbn__eizu = new global::ProtoBuf.DiscriminatedUnion32Object(2, value);
    }
    public bool ShouldSerializeEizp() => __pbn__eizu.Is(2);
    public void ResetEizp() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__eizu, 2);

    [global::ProtoBuf.ProtoMember(4, Name = @"eizr")]
    public int Eizr
    {
        get => __pbn__eizu.Is(4) ? __pbn__eizu.Int32 : default;
        set => __pbn__eizu = new global::ProtoBuf.DiscriminatedUnion32Object(4, value);
    }
    public bool ShouldSerializeEizr() => __pbn__eizu.Is(4);
    public void ResetEizr() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__eizu, 4);

    [global::ProtoBuf.ProtoMember(5, Name = @"eizt")]
    public Jjz Eizt
    {
        get => __pbn__eizu.Is(5) ? ((Jjz)__pbn__eizu.Object) : default;
        set => __pbn__eizu = new global::ProtoBuf.DiscriminatedUnion32Object(5, value);
    }
    public bool ShouldSerializeEizt() => __pbn__eizu.Is(5);
    public void ResetEizt() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__eizu, 5);

    public EizuOneofCase EizuCase => (EizuOneofCase)__pbn__eizu.Discriminator;

    public enum EizuOneofCase
    {
        None = 0,
        Eizn = 1,
        Eizp = 2,
        Eizr = 4,
        Eizt = 5,
    }

    [global::ProtoBuf.ProtoContract(Name = @"jjz")]
    public partial class Jjz : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jjz";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"eizg")]
        public required int Eizg { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"eizh")]
        public required int Eizh { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"eizi")]
        public required int Eizi { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
