// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jkv.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class BreachBranch : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jkv";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ejff")]
    public required global::System.Collections.Generic.List<MonsterInGroupInformation> Ejffs { get; set; } = new global::System.Collections.Generic.List<MonsterInGroupInformation>();

    [global::ProtoBuf.ProtoMember(2, Name = @"ejfg")]
    public required global::System.Collections.Generic.List<MonsterInGroupInformation> Ejfgs { get; set; } = new global::System.Collections.Generic.List<MonsterInGroupInformation>();

    [global::ProtoBuf.ProtoMember(3, Name = @"ejfh")]
    public required int Ejfh { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ejfi")]
    public required int Ejfi { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ejfj")]
    public required int Ejfj { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"ejfk")]
    public required long Ejfk { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"ejfl")]
    public required int Ejfl { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"ejfm")]
    public required Jkt Ejfm { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"jkt")]
    public partial class Jkt : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jkt";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ejex")]
        public required global::System.Collections.Generic.List<BreachReward> Ejexs { get; set; } = new global::System.Collections.Generic.List<BreachReward>();

        [global::ProtoBuf.ProtoMember(2, Name = @"ejey")]
        public required int Ejey { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ejez")]
        public int Ejez
        {
            get => __pbn__Ejez.GetValueOrDefault();
            set => __pbn__Ejez = value;
        }
        public bool ShouldSerializeEjez() => __pbn__Ejez != null;
        public void ResetEjez() => __pbn__Ejez = null;
        private int? __pbn__Ejez;

        [global::ProtoBuf.ProtoMember(4, Name = @"ejfb")]
        public required int Ejfb { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
