// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jlh.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightMark : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jlh";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ejgx")]
    public required int Ejgx { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ejgy")]
    public required global::System.Collections.Generic.List<Jlf> Ejgies { get; set; } = new global::System.Collections.Generic.List<Jlf>();

    [global::ProtoBuf.ProtoMember(3, Name = @"ejgz")]
    public required Jlc Ejgz { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ejha")]
    public required int Ejha { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ejhb")]
    public required int Ejhb { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"ejhc")]
    public required long Ejhc { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"ejhd")]
    public required Jdd Ejhd { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"ejhe")]
    public required bool Ejhe { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"ejhf")]
    public required int Ejhf { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"jlf")]
    public partial class Jlf : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jlf";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ejgq")]
        public required Jld Ejgq { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ejgr")]
        public required int Ejgr { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ejgs")]
        public required int Ejgs { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ejgt")]
        public required int Ejgt { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"jld")]
        public enum Jld
        {
            [global::ProtoBuf.ProtoEnum(Name = @"JLD_DRJU")]
            JldDrju = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"JLD_DRJV")]
            JldDrjv = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"JLD_DRJW")]
            JldDrjw = 2,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"jlc")]
    public enum Jlc
    {
        [global::ProtoBuf.ProtoEnum(Name = @"JLC_DRJP")]
        JlcDrjp = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"JLC_DRJQ")]
        JlcDrjq = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"JLC_DRJR")]
        JlcDrjr = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"JLC_DRJS")]
        JlcDrjs = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"JLC_DRJT")]
        JlcDrjt = 4,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
