// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jls.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class GuildInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jls";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ejjl")]
    public required int Ejjl { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ejjm")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ejjm { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"ejjn")]
    public required int Ejjn { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ejjo")]
    public required Jlq Ejjo { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"jlq")]
    public partial class Jlq : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jlq";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ejjg")]
        public required SocialEmblem Ejjg { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ejjh")]
        public required Jlo Ejjh { get; set; }

        [global::ProtoBuf.ProtoContract(Name = @"jlo")]
        public partial class Jlo : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jlo";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"ejiv")]
            public required long Ejiv { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"ejiw")]
            public required int Ejiw { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"ejix")]
            public required GuildRecruitmentInformation Ejix { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"ejiy")]
            public required int Ejiy { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"ejiz")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Ejiz
            {
                get => __pbn__Ejiz ?? "";
                set => __pbn__Ejiz = value;
            }
            public bool ShouldSerializeEjiz() => __pbn__Ejiz != null;
            public void ResetEjiz() => __pbn__Ejiz = null;
            private string __pbn__Ejiz;

            [global::ProtoBuf.ProtoMember(6, Name = @"ejjb")]
            public required int Ejjb { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"ejjc")]
            public required int Ejjc { get; set; }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
