// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jly.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class TaxCollectorStaticInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jly";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ejkn")]
    public required int Ejkn { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ejko")]
    public required int Ejko { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ejkp")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ejkp { get; set; } = "";

    [global::ProtoBuf.ProtoMember(4, Name = @"ejkq")]
    public required long Ejkq { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ejkr")]
    public required AllianceInformation Ejkr { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
