// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jmc.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightRemovableEffect : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jmc";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ejkv")]
    public required long Ejkv { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ejkw")]
    public required int Ejkw { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ejkx")]
    public required int Ejkx { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"ejky")]
    public required int Ejky { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"ejkz")]
    public required int Ejkz { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"ejla")]
    public required Jma Ejla { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"ejlb")]
    public required int Ejlb { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ejlc")]
    public FightTemporarySpellImmunityEffect Ejlc
    {
        get => __pbn__ejlf.Is(2) ? ((FightTemporarySpellImmunityEffect)__pbn__ejlf.Object) : default;
        set => __pbn__ejlf = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeEjlc() => __pbn__ejlf.Is(2);
    public void ResetEjlc() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ejlf, 2);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__ejlf;

    [global::ProtoBuf.ProtoMember(4, Name = @"ejld")]
    public FightTriggeredEffect Ejld
    {
        get => __pbn__ejlf.Is(4) ? ((FightTriggeredEffect)__pbn__ejlf.Object) : default;
        set => __pbn__ejlf = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
    }
    public bool ShouldSerializeEjld() => __pbn__ejlf.Is(4);
    public void ResetEjld() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ejlf, 4);

    [global::ProtoBuf.ProtoMember(10, Name = @"ejle")]
    public FightTemporaryBoostEffect Ejle
    {
        get => __pbn__ejlf.Is(10) ? ((FightTemporaryBoostEffect)__pbn__ejlf.Object) : default;
        set => __pbn__ejlf = new global::ProtoBuf.DiscriminatedUnionObject(10, value);
    }
    public bool ShouldSerializeEjle() => __pbn__ejlf.Is(10);
    public void ResetEjle() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ejlf, 10);

    public EjlfOneofCase EjlfCase => (EjlfOneofCase)__pbn__ejlf.Discriminator;

    public enum EjlfOneofCase
    {
        None = 0,
        Ejlc = 2,
        Ejld = 4,
        Ejle = 10,
    }

    [global::ProtoBuf.ProtoContract(Name = @"jma")]
    public enum Jma
    {
        [global::ProtoBuf.ProtoEnum(Name = @"JMA_DRQG")]
        JmaDrqg = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"JMA_DRQH")]
        JmaDrqh = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"JMA_DRQI")]
        JmaDrqi = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"JMA_DRQJ")]
        JmaDrqj = 3,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
