// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jmf.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightRemovableEffectExtendedInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jmf";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ejlp")]
    public required int Ejlp { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ejlq")]
    public required FightRemovableEffect Ejlq { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ejlr")]
    public required long Ejlr { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ejls")]
    public required long Ejls { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
