// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jmi.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PrismInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jmi";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ejlw")]
    public required int Ejlw { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ejlx")]
    public required long Ejlx { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ejly")]
    public required PrismModule Ejly { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ejlz")]
    public required int Ejlz { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ejma")]
    public required PrismCristal Ejma { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"ejmb")]
    public int Ejmb
    {
        get => __pbn__Ejmb.GetValueOrDefault();
        set => __pbn__Ejmb = value;
    }
    public bool ShouldSerializeEjmb() => __pbn__Ejmb != null;
    public void ResetEjmb() => __pbn__Ejmb = null;
    private int? __pbn__Ejmb;

    [global::ProtoBuf.ProtoMember(7, Name = @"ejmd")]
    public required long Ejmd { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"ejme")]
    public required long Ejme { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"ejmf")]
    public required AllianceInformation Ejmf { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"ejmg")]
    public required Jmg Ejmg { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"jmg")]
    public enum Jmg
    {
        [global::ProtoBuf.ProtoEnum(Name = @"JMG_DRRY")]
        JmgDrry = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"JMG_DRRZ")]
        JmgDrrz = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"JMG_DRSA")]
        JmgDrsa = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"JMG_DRSB")]
        JmgDrsb = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"JMG_DRSC")]
        JmgDrsc = 4,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
