// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jmo.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightCommonInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jmo";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"type")]
    public required Jcy Type { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"teams_options")]
    public required global::System.Collections.Generic.List<FightOptionsInformation> TeamsOptions { get; set; } = new global::System.Collections.Generic.List<FightOptionsInformation>();

    [global::ProtoBuf.ProtoMember(3, Name = @"fight_id")]
    public required int FightId { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"teams_position", IsPacked = true)]
    public required global::System.Collections.Generic.List<int> TeamsPositions { get; set; } = new global::System.Collections.Generic.List<int>();

    [global::ProtoBuf.ProtoMember(5, Name = @"teams_information")]
    public required global::System.Collections.Generic.List<FightTeamInformation> TeamsInformations { get; set; } = new global::System.Collections.Generic.List<FightTeamInformation>();

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
