// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jmw.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class AlignmentInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jmw";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ejpx")]
    public required Jcr Ejpx { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ejpy")]
    public required int Ejpy { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ejpz")]
    public required Jmu Ejpz { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ejqa")]
    public required int Ejqa { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ejqb")]
    public required long Ejqb { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"ejqc")]
    public required long Ejqc { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"jmu")]
    public partial class Jmu : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jmu";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ejpo")]
        public required int Ejpo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ejpp")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Ejpp
        {
            get => __pbn__Ejpp ?? "";
            set => __pbn__Ejpp = value;
        }
        public bool ShouldSerializeEjpp() => __pbn__Ejpp != null;
        public void ResetEjpp() => __pbn__Ejpp = null;
        private string __pbn__Ejpp;

        [global::ProtoBuf.ProtoMember(3, Name = @"ejpr")]
        public required int Ejpr { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"ejps")]
        public required int Ejps { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"ejpt")]
        public required Jcu Ejpt { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
