// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jna.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightTeamInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jna";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(2, Name = @"leader_id")]
    public required long LeaderId { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ejqx")]
    public required Jcr Ejqx { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ejqy")]
    public required int Ejqy { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ejqz")]
    public required Jdd Ejqz { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"ejra")]
    public required Jcz Ejra { get; set; }

    [global::ProtoBuf.ProtoMember(1, Name = @"ejrb")]
    public FightTeamMembersInformation Ejrb
    {
        get => __pbn__ejrd.Is(1) ? ((FightTeamMembersInformation)__pbn__ejrd.Object) : default;
        set => __pbn__ejrd = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializeEjrb() => __pbn__ejrd.Is(1);
    public void ResetEjrb() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ejrd, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__ejrd;

    [global::ProtoBuf.ProtoMember(7, Name = @"ejrc")]
    public FightTeamLightInformation Ejrc
    {
        get => __pbn__ejrd.Is(7) ? ((FightTeamLightInformation)__pbn__ejrd.Object) : default;
        set => __pbn__ejrd = new global::ProtoBuf.DiscriminatedUnionObject(7, value);
    }
    public bool ShouldSerializeEjrc() => __pbn__ejrd.Is(7);
    public void ResetEjrc() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ejrd, 7);

    public EjrdOneofCase EjrdCase => (EjrdOneofCase)__pbn__ejrd.Discriminator;

    public enum EjrdOneofCase
    {
        None = 0,
        Ejrb = 1,
        Ejrc = 7,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
