// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jni.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class CharacterCharacteristics : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jni";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ejsg")]
    public required long Ejsg { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ejsh")]
    public required long Ejsh { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ejsi")]
    public required long Ejsi { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ejsj")]
    public required AlignmentInformation Ejsj { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ejsk")]
    public required long Ejsk { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"ejsl")]
    public required long Ejsl { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"ejsm")]
    public required int Ejsm { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"ejsn")]
    public required long Ejsn { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"ejso")]
    public required global::System.Collections.Generic.List<SpellModifier> Ejsoes { get; set; } = new global::System.Collections.Generic.List<SpellModifier>();

    [global::ProtoBuf.ProtoMember(10, Name = @"ejsp")]
    public required global::System.Collections.Generic.List<CharacterCharacteristic> Ejsps { get; set; } = new global::System.Collections.Generic.List<CharacterCharacteristic>();

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
