// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jnq.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class FightTeamMemberInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jnq";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ejtq")]
    public required long Ejtq { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ejtr")]
    public FightTeamMemberMonster Ejtr
    {
        get => __pbn__ejtv.Is(2) ? ((FightTeamMemberMonster)__pbn__ejtv.Object) : default;
        set => __pbn__ejtv = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeEjtr() => __pbn__ejtv.Is(2);
    public void ResetEjtr() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ejtv, 2);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__ejtv;

    [global::ProtoBuf.ProtoMember(3, Name = @"ejts")]
    public FightTeamMemberEntity Ejts
    {
        get => __pbn__ejtv.Is(3) ? ((FightTeamMemberEntity)__pbn__ejtv.Object) : default;
        set => __pbn__ejtv = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
    }
    public bool ShouldSerializeEjts() => __pbn__ejtv.Is(3);
    public void ResetEjts() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ejtv, 3);

    [global::ProtoBuf.ProtoMember(4, Name = @"ejtt")]
    public FightTeamMemberTaxCollector Ejtt
    {
        get => __pbn__ejtv.Is(4) ? ((FightTeamMemberTaxCollector)__pbn__ejtv.Object) : default;
        set => __pbn__ejtv = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
    }
    public bool ShouldSerializeEjtt() => __pbn__ejtv.Is(4);
    public void ResetEjtt() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ejtv, 4);

    [global::ProtoBuf.ProtoMember(5, Name = @"ejtu")]
    public FightTeamMemberCharacter Ejtu
    {
        get => __pbn__ejtv.Is(5) ? ((FightTeamMemberCharacter)__pbn__ejtv.Object) : default;
        set => __pbn__ejtv = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
    }
    public bool ShouldSerializeEjtu() => __pbn__ejtv.Is(5);
    public void ResetEjtu() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ejtv, 5);

    public EjtvOneofCase EjtvCase => (EjtvOneofCase)__pbn__ejtv.Discriminator;

    public enum EjtvOneofCase
    {
        None = 0,
        Ejtr = 2,
        Ejts = 3,
        Ejtt = 4,
        Ejtu = 5,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
