// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jon.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class Character : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jon";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(2, Name = @"id")]
    public required long Id { get; set; }

    [global::ProtoBuf.ProtoMember(1, Name = @"character_remodeling_information")]
    public CharacterRemodelingInformation CharacterRemodelingInformation
    {
        get => __pbn__complement.Is(1) ? ((CharacterRemodelingInformation)__pbn__complement.Object) : default;
        set => __pbn__complement = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializeCharacterRemodelingInformation() => __pbn__complement.Is(1);
    public void ResetCharacterRemodelingInformation() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__complement, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__complement;

    [global::ProtoBuf.ProtoMember(3, Name = @"character_basic_information")]
    public CharacterBasicInformation CharacterBasicInformationValue
    {
        get => __pbn__complement.Is(3) ? ((CharacterBasicInformation)__pbn__complement.Object) : default;
        set => __pbn__complement = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
    }
    public bool ShouldSerializeCharacterBasicInformationValue() => __pbn__complement.Is(3);
    public void ResetCharacterBasicInformationValue() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__complement, 3);

    public ComplementOneofCase ComplementCase => (ComplementOneofCase)__pbn__complement.Discriminator;

    public enum ComplementOneofCase
    {
        None = 0,
        CharacterRemodelingInformation = 1,
        CharacterBasicInformationValue = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CharacterBasicInformation : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".CharacterBasicInformation";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public required string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"level")]
        public int Level
        {
            get => __pbn__Level.GetValueOrDefault();
            set => __pbn__Level = value;
        }
        public bool ShouldSerializeLevel() => __pbn__Level != null;
        public void ResetLevel() => __pbn__Level = null;
        private int? __pbn__Level;

        [global::ProtoBuf.ProtoMember(1, Name = @"social_member")]
        public Jny SocialMember
        {
            get => __pbn__complement.Is(1) ? ((Jny)__pbn__complement.Object) : default;
            set => __pbn__complement = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeSocialMember() => __pbn__complement.Is(1);
        public void ResetSocialMember() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__complement, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__complement;

        [global::ProtoBuf.ProtoMember(2, Name = @"character_look")]
        public Joj CharacterLook
        {
            get => __pbn__complement.Is(2) ? ((Joj)__pbn__complement.Object) : default;
            set => __pbn__complement = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeCharacterLook() => __pbn__complement.Is(2);
        public void ResetCharacterLook() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__complement, 2);

        [global::ProtoBuf.ProtoMember(5, Name = @"rank")]
        public RankInformation Rank
        {
            get => __pbn__complement.Is(5) ? ((RankInformation)__pbn__complement.Object) : default;
            set => __pbn__complement = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeRank() => __pbn__complement.Is(5);
        public void ResetRank() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__complement, 5);

        public ComplementOneofCase ComplementCase => (ComplementOneofCase)__pbn__complement.Discriminator;

        public enum ComplementOneofCase
        {
            None = 0,
            SocialMember = 1,
            CharacterLook = 2,
            Rank = 5,
        }

        [global::ProtoBuf.ProtoContract(Name = @"jny")]
        public partial class Jny : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jny";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"account_id")]
            public required long AccountId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"ava_role_id")]
            public int AvaRoleId
            {
                get => __pbn__AvaRoleId.GetValueOrDefault();
                set => __pbn__AvaRoleId = value;
            }
            public bool ShouldSerializeAvaRoleId() => __pbn__AvaRoleId != null;
            public void ResetAvaRoleId() => __pbn__AvaRoleId = null;
            private int? __pbn__AvaRoleId;

            [global::ProtoBuf.ProtoMember(3, Name = @"hours_since_last_connection")]
            public required long HoursSinceLastConnection { get; set; }

            [global::ProtoBuf.ProtoMember(4, Name = @"gender")]
            public required Gender Gender { get; set; }

            [global::ProtoBuf.ProtoMember(5, Name = @"enrollment_date")]
            public required long EnrollmentDate { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"state")]
            public required Jcq State { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"ejva")]
            public required Jnw Ejva { get; set; }

            [global::ProtoBuf.ProtoMember(8, Name = @"ejvb")]
            public required int Ejvb { get; set; }

            [global::ProtoBuf.ProtoMember(9, Name = @"ejvc")]
            public required CharacterStatus Ejvc { get; set; }

            [global::ProtoBuf.ProtoMember(10, Name = @"ejvd")]
            public required int Ejvd { get; set; }

            [global::ProtoBuf.ProtoContract(Name = @"jnw")]
            public partial class Jnw : global::ProtoBuf.IExtensible, IProtoMessage
            {
                public static string TypeUrl => ".jnw";
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(1, Name = @"ejuj")]
                public required Jcr Ejuj { get; set; }

                [global::ProtoBuf.ProtoMember(2, Name = @"ejuk")]
                public required long Ejuk { get; set; }

                [global::ProtoBuf.ProtoMember(3, Name = @"ejul")]
                public required Jnu Ejul { get; set; }

                [global::ProtoBuf.ProtoMember(4, Name = @"ejum")]
                public required int Ejum { get; set; }

                [global::ProtoBuf.ProtoMember(5, Name = @"ejun")]
                public required int Ejun { get; set; }

                [global::ProtoBuf.ProtoMember(6, Name = @"ejuo")]
                public required bool Ejuo { get; set; }

                [global::ProtoBuf.ProtoMember(7, Name = @"ejup")]
                public required int Ejup { get; set; }

                [global::ProtoBuf.ProtoContract(Name = @"jnu")]
                public partial class Jnu : global::ProtoBuf.IExtensible, IProtoMessage
                {
                    public static string TypeUrl => ".jnu";
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"ejud")]
                    public required long Ejud { get; set; }

                    [global::ProtoBuf.ProtoMember(2, Name = @"ejue")]
                    [global::System.ComponentModel.DefaultValue("")]
                    public required string Ejue { get; set; } = "";

                    [global::ProtoBuf.ProtoMember(3, Name = @"ejuf")]
                    [global::ProtoBuf.ProtoMap]
                    public required global::System.Collections.Generic.Dictionary<long, int> Ejufs { get; set; } = new global::System.Collections.Generic.Dictionary<long, int>();

                }

            }

        }

        [global::ProtoBuf.ProtoContract(Name = @"joj")]
        public partial class Joj : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".joj";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(5, Name = @"look")]
            public required EntityLook Look { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"breed_id")]
            public required int BreedId { get; set; }

            [global::ProtoBuf.ProtoMember(1, Name = @"ejwo")]
            public AllianceInformation Ejwo
            {
                get => __pbn__complement.Is(1) ? ((AllianceInformation)__pbn__complement.Object) : default;
                set => __pbn__complement = new global::ProtoBuf.DiscriminatedUnion32Object(1, value);
            }
            public bool ShouldSerializeEjwo() => __pbn__complement.Is(1);
            public void ResetEjwo() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__complement, 1);

            private global::ProtoBuf.DiscriminatedUnion32Object __pbn__complement;

            [global::ProtoBuf.ProtoMember(2, Name = @"base_information")]
            public CharacterBaseInformation BaseInformation
            {
                get => __pbn__complement.Is(2) ? ((CharacterBaseInformation)__pbn__complement.Object) : default;
                set => __pbn__complement = new global::ProtoBuf.DiscriminatedUnion32Object(2, value);
            }
            public bool ShouldSerializeBaseInformation() => __pbn__complement.Is(2);
            public void ResetBaseInformation() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__complement, 2);

            [global::ProtoBuf.ProtoMember(3, Name = @"ejwq")]
            public GuildInformation Ejwq
            {
                get => __pbn__complement.Is(3) ? ((GuildInformation)__pbn__complement.Object) : default;
                set => __pbn__complement = new global::ProtoBuf.DiscriminatedUnion32Object(3, value);
            }
            public bool ShouldSerializeEjwq() => __pbn__complement.Is(3);
            public void ResetEjwq() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__complement, 3);

            [global::ProtoBuf.ProtoMember(4, Name = @"ejwr")]
            public int Ejwr
            {
                get => __pbn__complement.Is(4) ? __pbn__complement.Int32 : default;
                set => __pbn__complement = new global::ProtoBuf.DiscriminatedUnion32Object(4, value);
            }
            public bool ShouldSerializeEjwr() => __pbn__complement.Is(4);
            public void ResetEjwr() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__complement, 4);

            public ComplementOneofCase ComplementCase => (ComplementOneofCase)__pbn__complement.Discriminator;

            public enum ComplementOneofCase
            {
                None = 0,
                Ejwo = 1,
                BaseInformation = 2,
                Ejwq = 3,
                Ejwr = 4,
            }

            [global::ProtoBuf.ProtoContract()]
            public partial class CharacterBaseInformation : global::ProtoBuf.IExtensible, IProtoMessage
            {
                public static string TypeUrl => ".CharacterBaseInformation";
                private global::ProtoBuf.IExtension __pbn__extensionData;
                global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                    => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                [global::ProtoBuf.ProtoMember(2, Name = @"ejwe")]
                public required Gender Ejwe { get; set; }

                [global::ProtoBuf.ProtoMember(1, Name = @"ejwf")]
                public Jod Ejwf
                {
                    get => __pbn__ejwi.Is(1) ? ((Jod)__pbn__ejwi.Object) : default;
                    set => __pbn__ejwi = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
                }
                public bool ShouldSerializeEjwf() => __pbn__ejwi.Is(1);
                public void ResetEjwf() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ejwi, 1);

                private global::ProtoBuf.DiscriminatedUnionObject __pbn__ejwi;

                [global::ProtoBuf.ProtoMember(3, Name = @"ejwg")]
                public Jof Ejwg
                {
                    get => __pbn__ejwi.Is(3) ? ((Jof)__pbn__ejwi.Object) : default;
                    set => __pbn__ejwi = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
                }
                public bool ShouldSerializeEjwg() => __pbn__ejwi.Is(3);
                public void ResetEjwg() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ejwi, 3);

                [global::ProtoBuf.ProtoMember(4, Name = @"ejwh")]
                public Joe Ejwh
                {
                    get => __pbn__ejwi.Is(4) ? ((Joe)__pbn__ejwi.Object) : default;
                    set => __pbn__ejwi = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
                }
                public bool ShouldSerializeEjwh() => __pbn__ejwi.Is(4);
                public void ResetEjwh() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ejwi, 4);

                public EjwiOneofCase EjwiCase => (EjwiOneofCase)__pbn__ejwi.Discriminator;

                public enum EjwiOneofCase
                {
                    None = 0,
                    Ejwf = 1,
                    Ejwg = 3,
                    Ejwh = 4,
                }

                [global::ProtoBuf.ProtoContract(Name = @"jod")]
                public partial class Jod : global::ProtoBuf.IExtensible, IProtoMessage
                {
                    public static string TypeUrl => ".jod";
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"ejvh")]
                    public required int Ejvh { get; set; }

                    [global::ProtoBuf.ProtoMember(2, Name = @"ejvi")]
                    public required int Ejvi { get; set; }

                    [global::ProtoBuf.ProtoMember(3, Name = @"ejvj")]
                    public required Job Ejvj { get; set; }

                    [global::ProtoBuf.ProtoContract(Name = @"job")]
                    public enum Job
                    {
                        [global::ProtoBuf.ProtoEnum(Name = @"JOB_DSHT")]
                        JobDsht = 0,
                        [global::ProtoBuf.ProtoEnum(Name = @"JOB_DSHU")]
                        JobDshu = 1,
                        [global::ProtoBuf.ProtoEnum(Name = @"JOB_DSHV")]
                        JobDshv = 2,
                    }

                }

                [global::ProtoBuf.ProtoContract(Name = @"jof")]
                public partial class Jof : global::ProtoBuf.IExtensible, IProtoMessage
                {
                    public static string TypeUrl => ".jof";
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"ejvy")]
                    public required global::System.Collections.Generic.List<PartyEntity> Ejvies { get; set; } = new global::System.Collections.Generic.List<PartyEntity>();

                    [global::ProtoBuf.ProtoMember(2, Name = @"ejvz")]
                    public required MapExtendedCoordinates Ejvz { get; set; }

                    [global::ProtoBuf.ProtoMember(3, Name = @"ejwa")]
                    public required MapExtendedCoordinates Ejwa { get; set; }

                }

                [global::ProtoBuf.ProtoContract(Name = @"joe")]
                public partial class Joe : global::ProtoBuf.IExtensible, IProtoMessage
                {
                    public static string TypeUrl => ".joe";
                    private global::ProtoBuf.IExtension __pbn__extensionData;
                    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

                    [global::ProtoBuf.ProtoMember(1, Name = @"ejvn")]
                    public required int Ejvn { get; set; }

                    [global::ProtoBuf.ProtoMember(2, Name = @"ejvo")]
                    public required PartyUpdateCommonsInformation Ejvo { get; set; }

                    [global::ProtoBuf.ProtoMember(3, Name = @"ejvp")]
                    public required MapExtendedCoordinates Ejvp { get; set; }

                    [global::ProtoBuf.ProtoMember(4, Name = @"ejvq")]
                    public required global::System.Collections.Generic.List<PartyEntity> Ejvqs { get; set; } = new global::System.Collections.Generic.List<PartyEntity>();

                    [global::ProtoBuf.ProtoMember(5, Name = @"ejvr")]
                    public required Jcr Ejvr { get; set; }

                    [global::ProtoBuf.ProtoMember(6, Name = @"ejvs")]
                    public required CharacterStatus Ejvs { get; set; }

                    [global::ProtoBuf.ProtoMember(7, Name = @"ejvt")]
                    public int Ejvt
                    {
                        get => __pbn__Ejvt.GetValueOrDefault();
                        set => __pbn__Ejvt = value;
                    }
                    public bool ShouldSerializeEjvt() => __pbn__Ejvt != null;
                    public void ResetEjvt() => __pbn__Ejvt = null;
                    private int? __pbn__Ejvt;

                }

            }

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
