// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jox.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class PlayerSearch : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jox";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"search_by_character_name")]
    public SearchByCharacterName SearchByCharacterNameValue
    {
        get => __pbn__player_search.Is(1) ? ((SearchByCharacterName)__pbn__player_search.Object) : default;
        set => __pbn__player_search = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializeSearchByCharacterNameValue() => __pbn__player_search.Is(1);
    public void ResetSearchByCharacterNameValue() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__player_search, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__player_search;

    [global::ProtoBuf.ProtoMember(2, Name = @"search_by_account")]
    public SearchByAccount SearchByAccountValue
    {
        get => __pbn__player_search.Is(2) ? ((SearchByAccount)__pbn__player_search.Object) : default;
        set => __pbn__player_search = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeSearchByAccountValue() => __pbn__player_search.Is(2);
    public void ResetSearchByAccountValue() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__player_search, 2);

    public PlayerSearchValueOneofCase PlayerSearchValueCase => (PlayerSearchValueOneofCase)__pbn__player_search.Discriminator;

    public enum PlayerSearchValueOneofCase
    {
        None = 0,
        SearchByCharacterNameValue = 1,
        SearchByAccountValue = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SearchByCharacterName : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".SearchByCharacterName";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public required string Name { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SearchByAccount : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".SearchByAccount";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public required string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"tag")]
        [global::System.ComponentModel.DefaultValue("")]
        public required string Tag { get; set; } = "";

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
