// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jpd.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class InteractiveElement : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jpd";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"element_type_id")]
    public required int ElementTypeId { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"age_bonus")]
    public int AgeBonus
    {
        get => __pbn__AgeBonus.GetValueOrDefault();
        set => __pbn__AgeBonus = value;
    }
    public bool ShouldSerializeAgeBonus() => __pbn__AgeBonus != null;
    public void ResetAgeBonus() => __pbn__AgeBonus = null;
    private int? __pbn__AgeBonus;

    [global::ProtoBuf.ProtoMember(3, Name = @"on_current_map")]
    public required bool OnCurrentMap { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"element_id")]
    public required int ElementId { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"disabled_skills")]
    public required global::System.Collections.Generic.List<InteractiveElementSkill> DisabledSkills { get; set; } = new global::System.Collections.Generic.List<InteractiveElementSkill>();

    [global::ProtoBuf.ProtoMember(6, Name = @"enabled_skills")]
    public required global::System.Collections.Generic.List<InteractiveElementSkill> EnabledSkills { get; set; } = new global::System.Collections.Generic.List<InteractiveElementSkill>();

    [global::ProtoBuf.ProtoContract()]
    public partial class InteractiveElementSkill : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".InteractiveElementSkill";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"skill_id")]
        public required int SkillId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"skill_instance_uid")]
        public required int SkillInstanceUid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"name_id")]
        public int NameId
        {
            get => __pbn__NameId.GetValueOrDefault();
            set => __pbn__NameId = value;
        }
        public bool ShouldSerializeNameId() => __pbn__NameId != null;
        public void ResetNameId() => __pbn__NameId = null;
        private int? __pbn__NameId;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
