// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jpi.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class CharacterRemodelingInformation : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jpi";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ekaq")]
    public required int Ekaq { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ekar")]
    public required Jpg Ekar { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ekas")]
    public required int Ekas { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ekat")]
    public required Gender Ekat { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ekau", IsPacked = true)]
    public required global::System.Collections.Generic.List<int> Ekaus { get; set; } = new global::System.Collections.Generic.List<int>();

    [global::ProtoBuf.ProtoMember(6, Name = @"ekav")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ekav { get; set; } = "";

    [global::ProtoBuf.ProtoContract(Name = @"jpg")]
    public partial class Jpg : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jpg";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ekal")]
        public required int Ekal { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ekam")]
        public required int Ekam { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
