// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jpl.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class CharacterStatus : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jpl";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"message")]
    [global::System.ComponentModel.DefaultValue("")]
    public string Message
    {
        get => __pbn__Message ?? "";
        set => __pbn__Message = value;
    }
    public bool ShouldSerializeMessage() => __pbn__Message != null;
    public void ResetMessage() => __pbn__Message = null;
    private string __pbn__Message;

    [global::ProtoBuf.ProtoMember(2, Name = @"status")]
    public required Status StatusValue { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public enum Status
    {
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_OFFLINE")]
        StatusOffline = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_AVAILABLE")]
        StatusAvailable = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_IDLE")]
        StatusIdle = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_AFK")]
        StatusAfk = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_PRIVATE")]
        StatusPrivate = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_SOLO")]
        StatusSolo = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"STATUS_UNKNOWN")]
        StatusUnknown = 6,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
