// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jpq.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class TextInformationEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jpq";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"message_type")]
    public required TextInformationType MessageType { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"parameters")]
    public required global::System.Collections.Generic.List<string> Parameters { get; set; } = new global::System.Collections.Generic.List<string>();

    [global::ProtoBuf.ProtoMember(3, Name = @"message_id")]
    public required int MessageId { get; set; }

    [global::ProtoBuf.ProtoContract()]
    public enum TextInformationType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"TEXT_INFORMATION_MESSAGE")]
        TextInformationMessage = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TEXT_INFORMATION_ERROR")]
        TextInformationError = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"TEXT_INFORMATION_PVP")]
        TextInformationPvp = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"TEXT_INFORMATION_FIGHT_LOG")]
        TextInformationFightLog = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"TEXT_INFORMATION_POPUP")]
        TextInformationPopup = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"TEXT_LIVING_OBJECT")]
        TextLivingObject = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"TEXT_ENTITY_TALK")]
        TextEntityTalk = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"TEXT_INFORMATION_FIGHT")]
        TextInformationFight = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"TEXT_INFORMATION_EVENT")]
        TextInformationEvent = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"JPO_DSRD")]
        JpoDsrd = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"JPO_DSRE")]
        JpoDsre = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"JPO_DSRF")]
        JpoDsrf = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"JPO_DSRG")]
        JpoDsrg = 13,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
