// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jps.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class WhoIsEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jps";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ekbt")]
    public required GuildInformation Ekbt { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ekbu")]
    public required Jct Ekbu { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ekbv")]
    public required Jcq Ekbv { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ekbw")]
    public required bool Ekbw { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ekbx")]
    public required long Ekbx { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"ekby")]
    public required AllianceInformation Ekby { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"ekbz")]
    public required int Ekbz { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"ekca")]
    public required int Ekca { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"ekcb")]
    public required bool Ekcb { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"ekcc")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ekcc { get; set; } = "";

    [global::ProtoBuf.ProtoMember(11, Name = @"ekcd")]
    public required long Ekcd { get; set; }

    [global::ProtoBuf.ProtoMember(12, Name = @"ekce")]
    public required int Ekce { get; set; }

    [global::ProtoBuf.ProtoMember(13, Name = @"ekcf")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ekcf { get; set; } = "";

    [global::ProtoBuf.ProtoMember(14, Name = @"ekcg")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ekcg { get; set; } = "";

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
