// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jqg.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract(Name = @"jqg")]
public enum Jqg
{
    [global::ProtoBuf.ProtoEnum(Name = @"JQG_DSVM")]
    JqgDsvm = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"JQG_DSVN")]
    JqgDsvn = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"JQG_DSVO")]
    JqgDsvo = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"JQG_DSVP")]
    JqgDsvp = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"JQG_DSVQ")]
    JqgDsvq = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"JQG_DSVR")]
    JqgDsvr = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"JQG_DSVS")]
    JqgDsvs = 6,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
