// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jrg.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class CompassUpdateEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jrg";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(3, Name = @"ekhu")]
    public required MapCoordinates Ekhu { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ekhv")]
    public required Jra Ekhv { get; set; }

    [global::ProtoBuf.ProtoMember(1, Name = @"ekhw")]
    public Jrd Ekhw
    {
        get => __pbn__ekhy.Is(1) ? ((Jrd)__pbn__ekhy.Object) : default;
        set => __pbn__ekhy = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
    }
    public bool ShouldSerializeEkhw() => __pbn__ekhy.Is(1);
    public void ResetEkhw() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ekhy, 1);

    private global::ProtoBuf.DiscriminatedUnionObject __pbn__ekhy;

    [global::ProtoBuf.ProtoMember(2, Name = @"ekhx")]
    public Jre Ekhx
    {
        get => __pbn__ekhy.Is(2) ? ((Jre)__pbn__ekhy.Object) : default;
        set => __pbn__ekhy = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
    }
    public bool ShouldSerializeEkhx() => __pbn__ekhy.Is(2);
    public void ResetEkhx() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ekhy, 2);

    public EkhyOneofCase EkhyCase => (EkhyOneofCase)__pbn__ekhy.Discriminator;

    public enum EkhyOneofCase
    {
        None = 0,
        Ekhw = 1,
        Ekhx = 2,
    }

    [global::ProtoBuf.ProtoContract(Name = @"jrd")]
    public partial class Jrd : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jrd";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ekhj")]
        public required bool Ekhj { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"ekhk")]
        public required bool Ekhk { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ekhl")]
        public required long Ekhl { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"jre")]
    public partial class Jre : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jre";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ekhp")]
        [global::System.ComponentModel.DefaultValue("")]
        public required string Ekhp { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"ekhq")]
        public required long Ekhq { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
