// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jta.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class SurrenderInfoResponse : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jta";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ekop")]
    public required Jsy Ekop { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ekoq")]
    public required Jsq Ekoq { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ekor")]
    public required bool Ekor { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"jsy")]
    public partial class Jsy : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jsy";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ekog")]
        public Jsw Ekog
        {
            get => __pbn__ekol.Is(1) ? ((Jsw)__pbn__ekol.Object) : default;
            set => __pbn__ekol = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeEkog() => __pbn__ekol.Is(1);
        public void ResetEkog() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ekol, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__ekol;

        [global::ProtoBuf.ProtoMember(2, Name = @"ekoh")]
        public Jss Ekoh
        {
            get => __pbn__ekol.Is(2) ? ((Jss)__pbn__ekol.Object) : default;
            set => __pbn__ekol = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeEkoh() => __pbn__ekol.Is(2);
        public void ResetEkoh() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ekol, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"ekoi")]
        public Jsu Ekoi
        {
            get => __pbn__ekol.Is(3) ? ((Jsu)__pbn__ekol.Object) : default;
            set => __pbn__ekol = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeEkoi() => __pbn__ekol.Is(3);
        public void ResetEkoi() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ekol, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"ekoj")]
        public Jsv Ekoj
        {
            get => __pbn__ekol.Is(4) ? ((Jsv)__pbn__ekol.Object) : default;
            set => __pbn__ekol = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeEkoj() => __pbn__ekol.Is(4);
        public void ResetEkoj() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ekol, 4);

        [global::ProtoBuf.ProtoMember(5, Name = @"ekok")]
        public Jst Ekok
        {
            get => __pbn__ekol.Is(5) ? ((Jst)__pbn__ekol.Object) : default;
            set => __pbn__ekol = new global::ProtoBuf.DiscriminatedUnionObject(5, value);
        }
        public bool ShouldSerializeEkok() => __pbn__ekol.Is(5);
        public void ResetEkok() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ekol, 5);

        public EkolOneofCase EkolCase => (EkolOneofCase)__pbn__ekol.Discriminator;

        public enum EkolOneofCase
        {
            None = 0,
            Ekog = 1,
            Ekoh = 2,
            Ekoi = 3,
            Ekoj = 4,
            Ekok = 5,
        }

        [global::ProtoBuf.ProtoContract(Name = @"jsw")]
        public partial class Jsw : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jsw";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"ekoc")]
            [global::System.ComponentModel.DefaultValue("")]
            public required string Ekoc { get; set; } = "";

        }

        [global::ProtoBuf.ProtoContract(Name = @"jss")]
        public partial class Jss : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jss";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract(Name = @"jsu")]
        public partial class Jsu : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jsu";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"eknt")]
            public required int Eknt { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"eknu")]
            public required int Eknu { get; set; }

        }

        [global::ProtoBuf.ProtoContract(Name = @"jsv")]
        public partial class Jsv : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jsv";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"ekny")]
            [global::ProtoBuf.ProtoMap]
            public required global::System.Collections.Generic.Dictionary<string, int> Eknies { get; set; } = new global::System.Collections.Generic.Dictionary<string, int>();

        }

        [global::ProtoBuf.ProtoContract(Name = @"jst")]
        public partial class Jst : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jst";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"eknp")]
            [global::ProtoBuf.ProtoMap]
            public required global::System.Collections.Generic.Dictionary<bool, int> Eknps { get; set; } = new global::System.Collections.Generic.Dictionary<bool, int>();

        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"jsq")]
    public partial class Jsq : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".jsq";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ekne")]
        public Jsn Ekne
        {
            get => __pbn__ekni.Is(1) ? ((Jsn)__pbn__ekni.Object) : default;
            set => __pbn__ekni = new global::ProtoBuf.DiscriminatedUnionObject(1, value);
        }
        public bool ShouldSerializeEkne() => __pbn__ekni.Is(1);
        public void ResetEkne() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ekni, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__ekni;

        [global::ProtoBuf.ProtoMember(2, Name = @"eknf")]
        public Jsm Eknf
        {
            get => __pbn__ekni.Is(2) ? ((Jsm)__pbn__ekni.Object) : default;
            set => __pbn__ekni = new global::ProtoBuf.DiscriminatedUnionObject(2, value);
        }
        public bool ShouldSerializeEknf() => __pbn__ekni.Is(2);
        public void ResetEknf() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ekni, 2);

        [global::ProtoBuf.ProtoMember(3, Name = @"ekng")]
        public Jsl Ekng
        {
            get => __pbn__ekni.Is(3) ? ((Jsl)__pbn__ekni.Object) : default;
            set => __pbn__ekni = new global::ProtoBuf.DiscriminatedUnionObject(3, value);
        }
        public bool ShouldSerializeEkng() => __pbn__ekni.Is(3);
        public void ResetEkng() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ekni, 3);

        [global::ProtoBuf.ProtoMember(4, Name = @"eknh")]
        public Jso Eknh
        {
            get => __pbn__ekni.Is(4) ? ((Jso)__pbn__ekni.Object) : default;
            set => __pbn__ekni = new global::ProtoBuf.DiscriminatedUnionObject(4, value);
        }
        public bool ShouldSerializeEknh() => __pbn__ekni.Is(4);
        public void ResetEknh() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__ekni, 4);

        public EkniOneofCase EkniCase => (EkniOneofCase)__pbn__ekni.Discriminator;

        public enum EkniOneofCase
        {
            None = 0,
            Ekne = 1,
            Eknf = 2,
            Ekng = 3,
            Eknh = 4,
        }

        [global::ProtoBuf.ProtoContract(Name = @"jsn")]
        public partial class Jsn : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jsn";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"ekmx")]
            public required int Ekmx { get; set; }

        }

        [global::ProtoBuf.ProtoContract(Name = @"jsm")]
        public partial class Jsm : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jsm";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract(Name = @"jsl")]
        public partial class Jsl : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jsl";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract(Name = @"jso")]
        public partial class Jso : global::ProtoBuf.IExtensible, IProtoMessage
        {
            public static string TypeUrl => ".jso";
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
