// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: juh.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class CharacterColors : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "juh";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ekud")]
    public required int Ekud { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ekue")]
    public required global::System.Collections.Generic.List<ColorPalette> Ekues { get; set; } = new global::System.Collections.Generic.List<ColorPalette>();

    [global::ProtoBuf.ProtoMember(3, Name = @"ekuf")]
    public required int Ekuf { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"ekug")]
    public required int Ekug { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
