// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jul.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract(Name = @"jul")]
public enum Jul
{
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRL")]
    JulDtrl = 0,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRM")]
    JulDtrm = 1,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRN")]
    JulDtrn = 2,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRO")]
    JulDtro = 3,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRP")]
    JulDtrp = 4,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRQ")]
    JulDtrq = 5,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRR")]
    JulDtrr = 6,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRS")]
    JulDtrs = 7,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRT")]
    JulDtrt = 8,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRU")]
    JulDtru = 9,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRV")]
    JulDtrv = 10,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRW")]
    JulDtrw = 11,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRX")]
    JulDtrx = 12,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRY")]
    JulDtry = 13,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTRZ")]
    JulDtrz = 14,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTSA")]
    JulDtsa = 15,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTSB")]
    JulDtsb = 16,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTSC")]
    JulDtsc = 17,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTSD")]
    JulDtsd = 18,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTSE")]
    JulDtse = 19,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTSF")]
    JulDtsf = 20,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTSG")]
    JulDtsg = 21,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTSH")]
    JulDtsh = 22,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTSI")]
    JulDtsi = 23,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTSJ")]
    JulDtsj = 24,
    [global::ProtoBuf.ProtoEnum(Name = @"JUL_DTSK")]
    JulDtsk = 25,
}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
