// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jux.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class Outfit : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jux";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ekwo")]
    public int Ekwo
    {
        get => __pbn__Ekwo.GetValueOrDefault();
        set => __pbn__Ekwo = value;
    }
    public bool ShouldSerializeEkwo() => __pbn__Ekwo != null;
    public void ResetEkwo() => __pbn__Ekwo = null;
    private int? __pbn__Ekwo;

    [global::ProtoBuf.ProtoMember(2, Name = @"ekwq")]
    public required EntityLook Ekwq { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"ekwr")]
    public int Ekwr
    {
        get => __pbn__Ekwr.GetValueOrDefault();
        set => __pbn__Ekwr = value;
    }
    public bool ShouldSerializeEkwr() => __pbn__Ekwr != null;
    public void ResetEkwr() => __pbn__Ekwr = null;
    private int? __pbn__Ekwr;

    [global::ProtoBuf.ProtoMember(4, Name = @"ekwt")]
    public required bool Ekwt { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"ekwu")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ekwu { get; set; } = "";

    [global::ProtoBuf.ProtoMember(6, Name = @"ekwv")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ekwv { get; set; } = "";

    [global::ProtoBuf.ProtoMember(7, Name = @"ekww")]
    public required ColorPalette Ekww { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"ekwx")]
    public required int Ekwx { get; set; }

    [global::ProtoBuf.ProtoMember(9, Name = @"ekwy")]
    public int Ekwy
    {
        get => __pbn__Ekwy.GetValueOrDefault();
        set => __pbn__Ekwy = value;
    }
    public bool ShouldSerializeEkwy() => __pbn__Ekwy != null;
    public void ResetEkwy() => __pbn__Ekwy = null;
    private int? __pbn__Ekwy;

    [global::ProtoBuf.ProtoMember(10, Name = @"ekxa")]
    public required int Ekxa { get; set; }

    [global::ProtoBuf.ProtoMember(11, Name = @"ekxb")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Ekxb { get; set; } = "";

    [global::ProtoBuf.ProtoMember(12, Name = @"ekxc")]
    [global::ProtoBuf.ProtoMap]
    public required global::System.Collections.Generic.Dictionary<int, Outfit.Juv> Ekxcs { get; set; } = new global::System.Collections.Generic.Dictionary<int, Outfit.Juv>();

    [global::ProtoBuf.ProtoContract(Name = @"juv")]
    public partial class Juv : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".juv";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ekwi")]
        public int Ekwi
        {
            get => __pbn__Ekwi.GetValueOrDefault();
            set => __pbn__Ekwi = value;
        }
        public bool ShouldSerializeEkwi() => __pbn__Ekwi != null;
        public void ResetEkwi() => __pbn__Ekwi = null;
        private int? __pbn__Ekwi;

        [global::ProtoBuf.ProtoMember(2, Name = @"ekwk")]
        public required int Ekwk { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
