// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jvf.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class OutfitEquipObjectBestSlotRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jvf";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"ekyu")]
    public required int Ekyu { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"ekyv")]
    public int Ekyv
    {
        get => __pbn__Ekyv.GetValueOrDefault();
        set => __pbn__Ekyv = value;
    }
    public bool ShouldSerializeEkyv() => __pbn__Ekyv != null;
    public void ResetEkyv() => __pbn__Ekyv = null;
    private int? __pbn__Ekyv;

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
