// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: jza.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class AllianceSummaryRequest : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "jza";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eloo")]
    public required int Eloo { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"elop")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Elop { get; set; } = "";

    [global::ProtoBuf.ProtoMember(3, Name = @"eloq")]
    public required bool Eloq { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"elor")]
    public required bool Elor { get; set; }

    [global::ProtoBuf.ProtoMember(5, Name = @"elos")]
    public required int Elos { get; set; }

    [global::ProtoBuf.ProtoMember(6, Name = @"elot")]
    public required long Elot { get; set; }

    [global::ProtoBuf.ProtoMember(7, Name = @"elou")]
    public required Jyy Elou { get; set; }

    [global::ProtoBuf.ProtoMember(8, Name = @"elov", IsPacked = true)]
    public required global::System.Collections.Generic.List<int> Elovs { get; set; } = new global::System.Collections.Generic.List<int>();

    [global::ProtoBuf.ProtoMember(9, Name = @"elow")]
    public required Jyx Elow { get; set; }

    [global::ProtoBuf.ProtoMember(10, Name = @"elox")]
    public required long Elox { get; set; }

    [global::ProtoBuf.ProtoMember(11, Name = @"eloy", IsPacked = true)]
    public required global::System.Collections.Generic.List<int> Eloys { get; set; } = new global::System.Collections.Generic.List<int>();

    [global::ProtoBuf.ProtoMember(12, Name = @"eloz")]
    public required bool Eloz { get; set; }

    [global::ProtoBuf.ProtoMember(13, Name = @"elpa", IsPacked = true)]
    public required global::System.Collections.Generic.List<Jdj> Elpas { get; set; } = new global::System.Collections.Generic.List<Jdj>();

    [global::ProtoBuf.ProtoContract(Name = @"jyy")]
    public enum Jyy
    {
        [global::ProtoBuf.ProtoEnum(Name = @"JYY_DURB")]
        JyyDurb = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"JYY_DURC")]
        JyyDurc = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"JYY_DURD")]
        JyyDurd = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"JYY_DURE")]
        JyyDure = 3,
    }

    [global::ProtoBuf.ProtoContract(Name = @"jyx")]
    public enum Jyx
    {
        [global::ProtoBuf.ProtoEnum(Name = @"JYX_DUQY")]
        JyxDuqy = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"JYX_DUQZ")]
        JyxDuqz = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"JYX_DURA")]
        JyxDura = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
