// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: kai.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class ConsoleMessage : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "kai";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"eltv")]
    public required Kag Eltv { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"eltw")]
    [global::System.ComponentModel.DefaultValue("")]
    public required string Eltw { get; set; } = "";

    [global::ProtoBuf.ProtoContract(Name = @"kag")]
    public enum Kag
    {
        [global::ProtoBuf.ProtoEnum(Name = @"KAG_DUYC")]
        KagDuyc = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"KAG_DUYD")]
        KagDuyd = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"KAG_DUYE")]
        KagDuye = 2,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
