// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: kav.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class Achievement : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "kav";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"elvq")]
    public required global::System.Collections.Generic.List<Kat> Elvqs { get; set; } = new global::System.Collections.Generic.List<Kat>();

    [global::ProtoBuf.ProtoMember(2, Name = @"elvr")]
    public required int Elvr { get; set; }

    [global::ProtoBuf.ProtoContract(Name = @"kat")]
    public partial class Kat : global::ProtoBuf.IExtensible, IProtoMessage
    {
        public static string TypeUrl => ".kat";
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"elvj")]
        public required long Elvj { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"elvk")]
        public required int Elvk { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"elvl")]
        public long Elvl
        {
            get => __pbn__Elvl.GetValueOrDefault();
            set => __pbn__Elvl = value;
        }
        public bool ShouldSerializeElvl() => __pbn__Elvl != null;
        public void ResetElvl() => __pbn__Elvl = null;
        private long? __pbn__Elvl;

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
