// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: kbe.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class AchievedAchievement : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "kbe";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"finished_level")]
    public int FinishedLevel
    {
        get => __pbn__FinishedLevel.GetValueOrDefault();
        set => __pbn__FinishedLevel = value;
    }
    public bool ShouldSerializeFinishedLevel() => __pbn__FinishedLevel != null;
    public void ResetFinishedLevel() => __pbn__FinishedLevel = null;
    private int? __pbn__FinishedLevel;

    [global::ProtoBuf.ProtoMember(2, Name = @"pioneer_rank")]
    public required int PioneerRank { get; set; }

    [global::ProtoBuf.ProtoMember(3, Name = @"achievement_id")]
    public required int AchievementId { get; set; }

    [global::ProtoBuf.ProtoMember(4, Name = @"achieved_by")]
    public required long AchievedBy { get; set; }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
