// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: kbi.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
[global::ProtoBuf.ProtoContract()]
public partial class GuestLimitationEvent : global::ProtoBuf.IExtensible, IProtoMessage
{
    public static string TypeUrl => "kbi";
    private global::ProtoBuf.IExtension __pbn__extensionData;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
        => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    [global::ProtoBuf.ProtoMember(1, Name = @"elxp")]
    public required Kbg Elxp { get; set; }

    [global::ProtoBuf.ProtoMember(2, Name = @"elxq")]
    public long Elxq
    {
        get => __pbn__Elxq.GetValueOrDefault();
        set => __pbn__Elxq = value;
    }
    public bool ShouldSerializeElxq() => __pbn__Elxq != null;
    public void ResetElxq() => __pbn__Elxq = null;
    private long? __pbn__Elxq;

    [global::ProtoBuf.ProtoContract(Name = @"kbg")]
    public enum Kbg
    {
        [global::ProtoBuf.ProtoEnum(Name = @"KBG_DVCW")]
        KbgDvcw = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"KBG_DVCX")]
        KbgDvcx = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"KBG_DVCY")]
        KbgDvcy = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"KBG_DVCZ")]
        KbgDvcz = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"KBG_DVDA")]
        KbgDvda = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"KBG_DVDB")]
        KbgDvdb = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"KBG_DVDC")]
        KbgDvdc = 6,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
