using Npgsql;

namespace Bubble.Core.Database;

public interface IEntityProperties : IEntitySql
{
    public bool MustBeDeleted { get; set; }
    public bool IsNew { get; set; }
    public bool IsDirty();
    public void ResetDirty();
}

public interface IEntitySql
{
    string GetInsertSql();

    NpgsqlParameter[] GetParameters();
    string GetRemoveSql();
    string GetUpdateSql();
}

public interface IEntityRecord<out T> : IEntityProperties
    where T : class
{
    static abstract string TableName { get; }
    static abstract string AutoGeneratedField { get; }
    static abstract bool HasAutoGeneratedField { get; }
    static abstract string SequenceName { get; }

    static abstract DatabaseTypes DatabaseType { get; }
    public object GetAutoGeneratedKey();

    static abstract T Map(NpgsqlDataReader reader);

    public void SetAutoGeneratedKey(object? key);
}