#nullable disable

namespace Bubble.SourceGenerators.Database.Models;

public sealed class DbColumn
{
    public int Index { get; set; }

    public string Name { get; set; }

    public string VariableName { get; set; }

    public string DbName { get; set; }

    public string FullType { get; set; }

    public bool IsRequired { get; set; }

    public bool IsNullable { get; set; }

    public bool IsReadOnly { get; set; }

    public bool IsInitOnly { get; set; }

    public bool IsValueType { get; set; }

    public bool IsAutoGenerated { get; set; }
}